### ISSUE TITLE
Playing a subtitle overshoots to the start of the next one

### ISSUE THREAD

**Issue by maltium** [SubtitleEdit/subtitleedit#3900] opened 2020-01-03 10:07 UTC
When selecting a subtitle and hitting play, some milliseconds of audio beyond the end marker is played. 

This issue can be easily reproduced by creating two subtitles, making sure the second one starts off where the previous one ends. Play the first subtitle, and then the second one. Notice that at the end of the first, some audio from the second one is played.

Although I understand that this is not problematic in most cases, this is significant issue when precision editing is required. Current workaround is to play the second subtitle to ensure that the end time of the first one is adjusted properly.

**Comment by xylographe** [comment] 2020-01-03 11:01
Which video engine?

**Comment by maltium** [comment] 2020-01-03 12:08
I'm using DirectShow, however I'm not dealing with video, just plain .ogg files. Changed over to mpv instead and the issue is also there.

The issue can also be seen visually on the timeline. The white line that indicates the position does not stop on the end time segment.

![image](https://user-images.githubusercontent.com/4674453/71722525-6a4a1c00-2e29-11ea-9854-d6f24dcf8bea.png)

**Comment by uckthis** [comment] 2020-01-05 05:33
@maltium Covert OGG  to mp3 and see.

**Comment by maltium** [comment] 2020-01-05 11:46
Issue happens irrespective of audio format (and both with constant and variable bitrates).

To make it clearer, I'm attaching a demo file. The audio file contains two sequential tones of different frequencies. The first subtitle encompasses the first tone, but when I play it, I hear part of the second tone at the end.

[demo.zip](https://github.com/SubtitleEdit/subtitleedit/files/4023332/demo.zip)

**Comment by OmrSi** [comment] 2020-01-06 19:40
Duplicate https://github.com/SubtitleEdit/subtitleedit/issues/2962

**Comment by niksedk** [comment] 2020-01-07 05:54
Closed as duplicate of  #706

**Closed by niksedk** 2020-01-07 05:54 UTC
