### ISSUE TITLE
Batch translate Request

### ISSUE THREAD

**Issue by vaccarieli** [SubtitleEdit/subtitleedit#4185] opened 2020-05-15 14:11 UTC
Is there a way to add an option to translate multiple files at once and not one by one ? 

I got 130 episodes I would like to translate, please help!

**Comment by xylographe** [comment] 2020-05-15 14:31
Menu **Tools > Batch convert...**

Or use SE from the command line. Run **`SubtitleEdit.exe /help`** to display more info.

**Comment by vaccarieli** [comment] 2020-05-15 14:42
> Menu **Tools > Batch convert...**
> 
> Or use SE from the command line. Run **`SubtitleEdit.exe /help`** to display more info.

Sorry, but there is no translate option on the > batch convert > convert options.

**Comment by OmrSi** [comment] 2020-05-15 17:04
A duplicate of https://github.com/SubtitleEdit/subtitleedit/issues/3612...

**Closed** 2020-05-15 17:34 UTC

**Comment by orbittwz** [comment] 2020-12-08 19:37
this request is looping with closed issues...
can someone implement this option for future SE versions? VASE doesn't work well as of now... (8/12/2020)
