### ISSUE TITLE
[BUG] Remove unneeded spaces several problems which destroys the subtitle if applied

### ISSUE THREAD

**Issue by marb99** [SubtitleEdit/subtitleedit#2118] opened 2016-11-27 21:45 UTC
Several problems with **Remove unneeded spaces** in SE 3.5.0 build 110 git- d28b1aa and in earlier recent builds.

Some examples of problems: language pt-pt

-----------------------------------------

Before fix remove unneeded spaces: "O pai do"

After fix remove unneeded spaces: "O **paido**"

-------------------------

Before fix remove unneeded spaces: "pai da"

After fix remove unneeded spaces: "**paida**"

-----------------------------------------------

Before fix remove unneeded spaces: "Lutei em países"

After fix remove unneeded spaces:  "**Luteiem** países"

--------------------------------------------------

Before fix remove unneeded spaces: "meu era"

After fix remove unneeded spaces:  "**meuera**"

------------------------------

Before fix remove unneeded spaces: "Avisei você"

After fix remove unneeded spaces:  "**Aviseivocê**"

------------------------------------------------------

Before fix remove unneeded spaces: "pai ser"

After fix remove unneeded spaces:  "**paiser**"

---------------------------------------------

Before fix remove unneeded spaces:  "virei buscá-las"

After fix remove unneeded spaces:  "**vireibuscá-las**"

---------------------------------------------------------------

**None of these spaces in the examples should be removed if applied the fix destroy the subtitle**

Are many problems and the option **"Remove unneeded spaces"** are broken I can not use this feature

All problems in the examples are in **bold**

I tested with the stable version of SE 3.5.0 and the same problem occurs.

I also tested in SE 3.4.13 and the problems remains.

here is a screenshot

![capturar](https://cloud.githubusercontent.com/assets/7856897/20652066/836b1ace-b4ea-11e6-8451-6033e0cc6c45.PNG)

here is the subtitle for test: 
[Ben-Hur.2016.zip](https://github.com/SubtitleEdit/subtitleedit/files/615076/Ben-Hur.2016.zip)

**Comment by ivandrofly** [comment] 2016-11-27 22:48
The problem is with => "¡" Subtiitle Edit removes all spaces before "¡"...  ¡ is not a valid portuguese character.

**Comment by marb99** [comment] 2016-11-27 23:13
@ivandrofly 

yes, well caught ^_^

is there an option to fix this automatically?

**Comment by ivandrofly** [comment] 2016-11-27 23:57
> is there an option in SE to fix this automatically?
> 
> Convert the Inverted exclamation mark to character "i"?

Well, It can be fixed by replacing all "¡" => i 

Note: After replace I'd recommend to check by using `Edit\Show history (for undo)` to make sure everything is replaced as expected :).

**Comment by marb99** [comment] 2016-11-28 00:53
@ivandrofly 

ok, thanks ;)

**Closed** 2016-11-29 18:54 UTC
