### ISSUE TITLE
UI unresponsive after Visual Sync

### ISSUE THREAD

**Issue by zorgoz** [SubtitleEdit/subtitleedit#3476] opened 2019-03-21 14:12 UTC
After performing visual synchronization, the UI becomes unresponsive. Subtitle window is updated, the asterisk appears after the file name in the main form caption, but can't save the file anymore. The program seems to be working as it consumes CPU and reacts to WM_CLOSE message, which makes the confirmation dialog appear. But that too is unresponsive. Only killing the process helps. The issue appears iregularly: sometimes I can sync several files before this happens, sometimes I need to restart it many times before I am able to save.

Loaded assemblies:
![image](https://user-images.githubusercontent.com/1569170/54757972-932b5880-4beb-11e9-9e26-bf50ab19c2ea.png)

OS: 2016, kernel build 10.0.14393

**Comment by niksedk** [comment] 2019-03-23 09:00
What video player inside SE are you using?

**Comment by zorgoz** [comment] 2019-03-25 10:26
These are my current video settings:
![image](https://user-images.githubusercontent.com/1569170/54912338-b5292180-4ef0-11e9-83af-95259fb2d278.png)

**Comment by niksedk** [comment] 2019-03-27 08:44
Hm, I cannot re-create this... is it all videos or only some?

**Comment by zorgoz** [comment] 2019-03-27 10:09
Well, I have been working on 72 videos. I could manage to sync many without a problem, and the others only after several or many attempts. But I don't know what would have happened if I would have tried the first shot good ones multiple times.

**Comment by dlong500** [comment] 2020-01-27 06:14
I have this issue too, except mine happens every single time.  So I basically can't even use visual sync.  Even if I just open visual sync and then immediately cancel it is still unresponsive.  It seems like something to do with mpv, as it doesn't occur if I use MPC-HC (my preferred player), but with MPC-HC I can't see any video (only sound) within SE.

**Comment by Ouroboros1995** [comment] 2020-01-29 15:47
Yes, I have the same problem, only with mpv. Mpv usually gives the best performance when it comes to video playback, but it makes visual sync unusable. UI becomes completely unresponsive.

**Comment by niksedk** [comment] 2020-01-29 19:40
How is latest beta regarding visual sync and mpv?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.13/SubtitleEditBeta.zip

**Comment by Ouroboros1995** [comment] 2020-01-29 19:51
Unfortunately, its still the same.

**Comment by niksedk** [comment] 2020-01-29 20:03
@Ouroboros1995: Could you test some of the different libmpv versions?
https://github.com/SubtitleEdit/support-files/commits/master/mpv/libmpv64.zip

( Even more builds are here: https://sourceforge.net/projects/mpv-player-windows/files/64bit/ )

**Comment by Ouroboros1995** [comment] 2020-01-29 20:41
I ve tried several of these, and its the same.

**Comment by Ouroboros1995** [comment] 2020-01-30 00:11
It works with without any issues with - **mpv-dev-20181002.**
I ve downloaded it from: https://mpv.srsfckn.biz/

**Comment by niksedk** [comment] 2020-01-30 05:42
@Ouroboros1995: What OS are you using? Gfx card?

**Comment by Ouroboros1995** [comment] 2020-01-30 12:38
> What OS are you using? Gfx card?

Windows 8.1 ang I have Asus NVIDIA GeForce GTS 450

**Comment by Ouroboros1995** [comment] 2020-01-31 12:14
So, still no solution to this? Its obvious that it has something to do with mpv player, but I can not even guess whats the problem exactly. I ve tried it on my other pc, and its the same with mpv player. As soon as I open visual sync, and then close it, UI becomes completely unresponsive.

**Comment by niksedk** [comment] 2020-01-31 12:46
I cannot guess what's the problem is either ;)
Is this beta any better: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.13/SubtitleEditBeta.zip ?

**Comment by Ouroboros1995** [comment] 2020-01-31 12:52
Actually it is, because I ve used the newest version of mpv with this beta and UI didnt get unresponsive, with previous versions of SE, whenever I use the latest version of mpv, UI instantly gets unresponsive, now thats not the case.

**Closed** 2020-01-31 13:11 UTC
