### ISSUE TITLE
[Feature request] Add OCR support to hardsubbed videos

### ISSUE THREAD

**Issue by Tizioincognit0** [SubtitleEdit/subtitleedit#5033] opened 2021-05-09 16:00 UTC
Hi, it's possible to add OCR support to hardsubbed videos?

**Comment by niksedk** [comment] 2021-05-09 16:04
Duplicate of https://github.com/SubtitleEdit/subtitleedit/issues/340

Perhaps this will work for you? https://www.videohelp.com/software/VideoSubFinder

**Closed by niksedk** 2021-05-09 16:04 UTC
Labels: duplicate
