### ISSUE TITLE
[Feature Request]:  Use continuous speech to text to generate subtitle text

### ISSUE THREAD

**Issue by kdx7214** [SubtitleEdit/subtitleedit#4190] opened 2020-05-19 20:59 UTC
Even if the text was wrong, having the timings down solid would really speed things up.  Also, there are a lot of open source libs out there for speech recognition now.

**Comment by niksedk** [comment] 2020-05-20 06:27
Duplicate of #1878

**Closed by niksedk** 2020-05-20 06:27 UTC

**Comment by niksedk** [comment] 2022-01-02 09:29
SE beta now has speech recognition built-it:

Open a video and click on "Video/audio to text"
![image](https://user-images.githubusercontent.com/1261331/147871741-0d2106f3-ffa9-409a-b40b-e9df5a4ca6d0.png)


https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip

**Comment by charuta2001** [comment] 2022-01-31 14:01
> SE beta now has speech recognition built-it:
> 
> Open a video and click on "Video/audio to text" ![image](https://user-images.githubusercontent.com/1261331/147871741-0d2106f3-ffa9-409a-b40b-e9df5a4ca6d0.png)
> 
> https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip

many many many thanks! made my life easier as a subtitlist! normally i transcribe and then do time coding in SE, this will make my life smooth! blessings!!!
