### ISSUE TITLE
can be building a MAC version?

### ISSUE THREAD

**Issue by Battlecraft369** [SubtitleEdit/subtitleedit#4965] opened 2021-04-08 08:35 UTC
can be building a MAC version? im useing MAC work...so...Plz...

**Comment by niksedk** [comment] 2021-04-08 09:25
Duplicate of https://github.com/SubtitleEdit/subtitleedit/issues/81

ATM a mac version will be really hard - at not cross platform gui for C# exists... 
It seems that MS is working on something though: https://github.com/dotnet/maui

**Closed by niksedk** 2021-04-08 09:25 UTC
Labels: duplicate
