### ISSUE TITLE
Release 3.5.15

### ISSUE THREAD

**Issue by niksedk** [SubtitleEdit/subtitleedit#4131] opened 2020-04-19 17:06 UTC
Some nice fixes and some nice new features - and a huge amount of minor improvements!

@Flitskikker added `sentence continuation style` - see https://github.com/SubtitleEdit/subtitleedit/pull/4108

Also, this version brings some sought after features: "Tesseract 5 Alpha", waveform for video with no audio, shortcuts F4-F12 customizable, more improvements for "Batch convert", improvements for "Fix common errors".

Check the full change log here: https://raw.githubusercontent.com/SubtitleEdit/subtitleedit/master/Changelog.txt

Please do give latest beta a run and report any bugs here :)
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.14/SubtitleEditBeta.zip

TODO:
- [x] Test Continuation style
- [x] Test "Batch convert"
- [x] Test Fix common errors
- [x] Test OCR
- [x]  General testing  (+ fixing bugs)

**Comment by OmrSi** [comment] 2020-04-19 17:08
You've been doing a lot of work. Thank you. :)

**Comment by Lero91** [comment] 2020-04-19 17:26
Great. I will definitely give this a try. Now, I took the liberty to update the Greek translation.
[Uploading Translation.zip…]()
Also, I came across this strange message on beta 334, while trying to create a waveform.
I tried immediately for a second time, and there was no issue. Strange.
![Σφάλμα](https://user-images.githubusercontent.com/63797709/79694866-dedf8400-827b-11ea-94e0-8abea6e1d6cb.jpg)

**Comment by xylographe** [comment] 2020-04-20 04:36
Updated Greek translation applied in commit 1772a156c7625d6a1e4294bd806702c050bedfc8.

**Comment by Lero91** [comment] 2020-04-20 15:32
Another error message, while trying to create a waveform. This time, on latest beta.
![Σφάλμα](https://user-images.githubusercontent.com/63797709/79769677-1827fa80-8335-11ea-8266-44491fb65633.jpg)

**Comment by Signy13** [comment] 2020-04-21 10:52
OCR tested with Tesseract 3 and 5 - everything looks OK (Linux, Wine 5.0, .NET 4.0).

**Comment by niksedk** [comment] 2020-04-21 17:05
SE should now ignore shortcuts when the `Windows-Key` is pressed ( commit 
https://github.com/SubtitleEdit/subtitleedit/commit/12d5feb5b81af75710e3040a71bc7eb93211f56c )

**Comment by Lero91** [comment] 2020-04-21 17:20
@niksedk: No, the wave file doesn't exist, when I get the message, and it appears instantly.
I say it's mostly random. Also, about the video player settings, when I uncheck the boxes for mute, stop and fullscreen options, they are checked back, when I restart the programme. Is this intentional?

**Comment by Signy13** [comment] 2020-04-21 20:20
@niksedk I went through a common Wine log file found some errors:
`0093:fixme:ras:RasEnumConnectionsW (06E4F5F8,0032DC64,0032DC68),stub!
0093:fixme:ras:RasEnumConnectionsW RAS support is not implemented! Configure program to use LAN connection/winsock instead!`
I have not found any solution for this error on the Internet.
Then I tested SubtitleEdit on Wine + .NET 4.7 and the downloading works now.  So there might be someting wrong with .NET 4.0...
However, it is still useful then SubtitleEdit can provide useful information when some download is not working :)

**Comment by niksedk** [comment] 2020-04-22 05:43
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.14/SubtitleEditBeta.zip

Fixed titlebar so it's now `*` + `name of the file` + `Subtitle Edit` (like Notepad), thx @Signy13 :)

@Lero91: Also fixed some of the video player buttons, thx :)

**Comment by Flitskikker** [comment] 2020-04-22 11:38
@niksedk 
One thing I found a while ago but falls under "Test OCR".
I have some pre-OCR'ed .srts that have a lowercase L instead of an uppercase i, in uppercase text:

![image](https://user-images.githubusercontent.com/3516155/79977274-4a08a080-849e-11ea-96f9-74c2d338d40c.png)

In FCE, there is "Fix uppercase 'i' inside lowercase words".
Would it be easy to also add "Fix lowercase 'L' inside uppercase words"?

**Comment by OmrSi** [comment] 2020-04-22 13:31
@niksedk Maybe "after" should be after the name and not at the end?
Also, there is no indication for the original.
My idea is, before means here and here:
![image](https://user-images.githubusercontent.com/20923700/79987869-9b248e80-84b6-11ea-9df6-594151496ea8.png)

And after means here and here:
![image](https://user-images.githubusercontent.com/20923700/79987896-a5468d00-84b6-11ea-88fb-734ef373a3fd.png)

**Comment by borifax** [comment] 2020-04-22 16:55
Thanks for fixing the error when the files with the .mts extension are not loaded (chat).
A similar error occurs with the file extension .eac3 when I trying to load it into waveform (SE does not "see" it).

![Schowek02](https://user-images.githubusercontent.com/45988475/80010451-ba2d1b80-84ca-11ea-9fef-5e2127e828fb.jpg)
![Schowek04](https://user-images.githubusercontent.com/45988475/80010454-bbf6df00-84ca-11ea-80ff-2366c82ad226.jpg)

**Comment by OmrSi** [comment] 2020-04-22 18:07
@niksedk Can you hide for Arabic in FCE:
Add period after lines where next line start with uppercase letter
Start with uppercase letter after paragraph
Start with uppercase letter after period inside paragraph
Start with uppercase letter after colon/semicolon
Fix uppercase 'i' inside lowercase words

They don't have a meaning in Arabic as it doesn't have upper and lowercase characters.

**Comment by uckthis** [comment] 2020-04-24 05:56
Why F11 & F12 default shortcuts were removed?

**Comment by niksedk** [comment] 2020-04-24 06:00
@uckthis: They should not be... was a bug in an earlier beta version. But shortcuts F4-F12 can be customized now.

**Comment by uckthis** [comment] 2020-04-24 06:08
@niksedk I already have Start and End time keys set. F11&F12 just gave the option of having multiple shortcuts doing the same thing. In my case both of them were used for different scenarios. My Set Start is Alt+[, which works effectively when I'm syncing an imported text, but during proofreading F11 was much easier as it's just one key.  But if more people want F11 and F12 free to be assigned, then I'll make do.

**Comment by niksedk** [comment] 2020-04-24 06:19
@uckthis: A solution could be have double shortcuts - like for "F9"
![image](https://user-images.githubusercontent.com/1261331/80180966-34ad8680-8604-11ea-8003-1874be57e83e.png)
Would that help or be more confusing?

**Comment by uckthis** [comment] 2020-04-24 06:27
@niksedk Yes, that would surely solve the problem. "Add another" next to Clear button in shortcut page, that would work too. That would also allow to add multiple shortcuts for every command. And maybe colorize the new shortcut to differentiate. Let's see what others have to say.

**Comment by Signy13** [comment] 2020-04-24 07:13
> @niksedk Yes, that would surely solve the problem. "Add another" next to Clear button in shortcut page, that would work too. That would also allow to add multiple shortcuts for every command.

The new button between "Update" and "Clear" is a nice solution.

**Comment by borifax** [comment] 2020-04-24 08:09
Is it possible to set the time with an accuracy of 0.01 sec. after each click on the "waveform" field?
The accuracy is currently 0.001 sec.

![Schowek01](https://user-images.githubusercontent.com/45988475/80189782-8ad5f600-8613-11ea-9f3b-e55f2faa6e80.jpg)

**Comment by OmrSi** [comment] 2020-04-24 13:14
@uckthis I had the same opinion when this was done, but he said people are asking to customize F4-F12 so I made do.
But I think adding an "Add another" is a bit complicated, he would have to edit the code for each shortcut, I'm guessing.

**Comment by uckthis** [comment] 2020-04-24 13:43
@OmrSi I don't know programming at all, but I think it's going to be one condition that will apply all.

**Comment by OmrSi** [comment] 2020-04-24 13:46
@uckthis Based on what I've seen, he'd have to add another parameter to each condition of the shortcuts and would have to make it duplicate every entry in the settings file.

**Comment by uckthis** [comment] 2020-04-24 13:51
@OmrSi If it's that much trouble, then let's just forget it.

**Comment by OmrSi** [comment] 2020-04-25 17:45
@Flitskikker I just got to test the `sentence continuation style` with Arabic.
You need to add the Arabic comma `،` and add the Arabic question mark `؟` as a line ending.
![image](https://user-images.githubusercontent.com/20923700/80286677-70943900-8735-11ea-9ad3-241ae8f9bdb0.png)
The line ends with a question mark, which means it's a full sentence.

![image](https://user-images.githubusercontent.com/20923700/80286689-89045380-8735-11ea-876e-ed6051d66928.png)
The first line ends with a comma, I'm using `None, dots for pauses` so it shouldn't be removed replaced.

**Comment by OmrSi** [comment] 2020-04-25 18:02
@niksedk Using the `remove all formatting` shortcut is making the list go to the top.
![Untitled Project](https://user-images.githubusercontent.com/20923700/80287035-cff34880-8737-11ea-81b7-0cafbde9e53c.gif)

And something in this file, in the tags, is causing FCE to crash:
![image](https://user-images.githubusercontent.com/20923700/80287056-e0a3be80-8737-11ea-9c1a-d38f8d6c5b7e.png)
[Bloodshot 2020 BluRay (Colored).zip](https://github.com/SubtitleEdit/subtitleedit/files/4533686/Bloodshot.2020.BluRay.Colored.zip)

**Comment by Ouroboros1995** [comment] 2020-04-25 18:10
Great work. Best program for subtitles.

**Comment by Flitskikker** [comment] 2020-04-25 18:18
@OmrSi 
Thanks for the report and the file, going to look into it.

Would the continuation style make sense at all for Arabic at the moment? Looks like it's adding the trailing dots - that should be at the ending - at the front of the sentence because it's RTL.

**Comment by OmrSi** [comment] 2020-04-25 18:27
@Flitskikker In general, SE works with the file before reversing.
So, one should do FCE then reverse the file, other rules apply this way also.
So you can treat it as it is before reversing. :D

**Comment by Flitskikker** [comment] 2020-04-25 19:29
@OmrSi 
I have fixed the crash. Wasn't specific to Arabic, it was caused by stripped { } tags so it would have crashed on other languages too. So good catch!

Could you explain the reversing? The logic relies a lot on the actual sentence continuation, so it detects beginnings and ends of sentences. For example, it checks if the first character is a capital letter. Wouldn't that fail on Arabic, because the first character is a dot or question mark?

**Comment by OmrSi** [comment] 2020-04-25 19:36
Hmm.
Well, we translate the file then reverse it, so it can be used before reversing and it should work fine.
You have two ways of reversing which could be found in the Edit menu.
But as I said, it can be used before reversing.
How would it work? Well, the same as English but without the case of the letter.
If the line doesn't end with anything, it checks the gap and works based on that.
If the file is already reversed, the translator can just uncheck the option.
You just need to add the Arabic question mark as a line ending and the Arabic comma as an alternative comma.

**Comment by OmrSi** [comment] 2020-04-25 19:36
@niksedk Using the `remove all formatting` shortcut is making the list go to the top.
![Untitled Project](https://user-images.githubusercontent.com/20923700/80287035-cff34880-8737-11ea-81b7-0cafbde9e53c.gif)

**Comment by Flitskikker** [comment] 2020-04-25 20:14
@OmrSi 
I added some basic support (it just converts the comma and question mark before and after, because there's a lot going on internally based on the comma). Maybe you can pull it locally and test if it works?
https://github.com/SubtitleEdit/subtitleedit/pull/4150

**Comment by OmrSi** [comment] 2020-04-26 01:21
@Flitskikker It's working well. :D
I have a question and a request.
The question, in `None, dots for pauses (trailing only)` are commas always kept or just for consecutive subtitles?

The request, can you make it just ignore the line if it was all in quotes?
We use it for on-screen text, we right the subtitle in quotes and don't end it with a dot.

**Comment by moob158** [comment] 2020-04-26 01:24
@Flitskikker the continuation should not replace the comma in the end of line, the comma is a kind of continuation.

and the tooltip in combobox should be remove, the tooltip is useful for non english read the entire content of combobox because the combox is too small for read the translations of SE

**Comment by uckthis** [comment] 2020-04-26 10:41
Remove unneeded space doesn't work in italics.
Example:
<i>I happen to have
the blood of an ancient family .</i>

It doesn't fix the space before period.

**Comment by Flitskikker** [comment] 2020-04-26 11:04
@OmrSi 
Great! Could you send me a test file that contains on-screen text?

@Flitskikker 
Which continuation style do you have set? When it's set to none, it keeps the comma.
When it's set to "Dots", for example, any sentence that ends with a comma is seen as a continuing sentence. Thus, it will apply the continuation style. Effectively, replacing the comma with dots. This is what happens in every subtitle I've checked (for languages that use dots).

I'm not sure what you mean regarding the tooltip. It uses lorem ipsum for all SE languages. Could you please explain?

**Comment by niksedk** [comment] 2020-04-26 12:03
@OmrSi: thx, after 'remove all formatting' first selected line should be selected (if lines were removed).
@uckthis: thx, remove spaces issue should be fixed now.

Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.14/SubtitleEditBeta.zip

**Comment by Lero91** [comment] 2020-04-26 12:13
Further translation improvements and updates. Keep up the good work, Nikolaj. This release is shaping up really great.
[Translation.zip](https://github.com/SubtitleEdit/subtitleedit/files/4535262/Translation.zip)

**Comment by niksedk** [comment] 2020-04-26 13:45
@Lero91: thx, and thx for the translation update: https://github.com/SubtitleEdit/subtitleedit/commit/5853c3bf17e0c98e16f52a8cfb2e0f52467e9107

**Comment by OmrSi** [comment] 2020-04-26 13:58
@Flitskikker Sure. These all are On-screen: [On-Screen.zip](https://github.com/SubtitleEdit/subtitleedit/files/4535445/On-Screen.zip)

**Comment by OmrSi** [comment] 2020-04-26 14:00
@niksedk You seem ready for the new version.
I hope you can just wait a little for the last `sentence continuation style` pull request for Arabic from @Flitskikker :)

**Comment by Flitskikker** [comment] 2020-04-26 14:23
@OmrSi 
Thanks. Two questions:
- Should it only detect " ?
- Wouldn't these quotes be used for actual quotes in some cases? If so, how to differentiate a screen text vs a continuing quote?

**Comment by OmrSi** [comment] 2020-04-26 14:33
Yes, we only use `"`.
Well, the difference is that we end a normal quote with a punctuation mark, usually a dot, while we leave the on-screen text without a dot at the end.
I know there would still be some room for error because we don't have casing, but the translator would just have to check those, and adding this rule will lower the number a lot.

**Comment by OmrSi** [comment] 2020-04-26 14:37
Another thing that might help, if the line before the quoted line ends with a comma, then it's a quote without a doubt.

**Comment by Flitskikker** [comment] 2020-04-26 15:05
@OmrSi 
I've added some logic: https://github.com/SubtitleEdit/subtitleedit/pull/4152
If a subtitle is an insert (wrapped in quotes and ends with nothing) it will uncheck the fix by default.
Currently a hardcoded rule for Arabic; if it works I can add it to the settings UI in the next version.

**Comment by OmrSi** [comment] 2020-04-26 16:42
@Flitskikker Activating this is causing all lines to be unchecked in Arabic for some reason:
![image](https://user-images.githubusercontent.com/20923700/80313796-fb3c6d00-87f5-11ea-8f4d-9b1c00658108.png)

**Comment by Flitskikker** [comment] 2020-04-26 18:18
@OmrSi 
Could you please pull again and try it again with that option checked?
It should now ignore it for languages that don't have upper/lower case.

**Comment by moob158** [comment] 2020-04-26 18:30
@Flitskikker 

I can't read the entire content, translation is cut, the tooltip is useful for read this

![Sem Título](https://user-images.githubusercontent.com/60049180/80316176-1dcd8680-87f4-11ea-836e-451c066c743c.png)

**Comment by Flitskikker** [comment] 2020-04-26 18:45
@moob158 
Ah I understand. @niksedk, could you make the dropdown wider? (Apparently https://github.com/SubtitleEdit/subtitleedit/commit/8271fd5266686016930ce3ef2adeec9c0a9c1355 is not wide enough.)

**Comment by OmrSi** [comment] 2020-04-26 18:52
@Flitskikker Works well now. :D
Thank you for all the effort.
Ready to merge. 👌

**Comment by niksedk** [comment] 2020-04-26 18:55
Merged: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.14/SubtitleEditBeta.zip

@moob158: `Continuation drop down` should now auto size.

**Comment by OmrSi** [comment] 2020-04-26 18:57
411 commits. That's something. :D

**Comment by moob158** [comment] 2020-04-26 19:04
@niksedk and @Flitskikker 

thanks ;)

**Comment by borifax** [comment] 2020-04-26 19:13
Could you add the .mts extension?
Mts files are supported but appear only as "all files".
![1111](https://user-images.githubusercontent.com/45988475/80317216-bec33e00-8802-11ea-9d75-c92714305129.png)
![22222](https://user-images.githubusercontent.com/45988475/80317218-bf5bd480-8802-11ea-92c0-a0b4705fc878.png)

**Comment by niksedk** [comment] 2020-04-27 09:58
@borifax: Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.14/SubtitleEditBeta.zip

**Comment by OmrSi** [comment] 2020-04-27 13:49
@niksedk Any chance you can add these two shortcuts?
![image](https://user-images.githubusercontent.com/20923700/80379434-c3413280-88a6-11ea-8647-e269322cf605.png)

Link previous extends the previous line's end to the current's start.
Link next extends the next line's start to the current's end.
It's easier than moving to the previous/next subtitle and using extend.

**Comment by uckthis** [comment] 2020-04-27 14:01
@OmrSi Use bridge gap.

**Comment by Lero91** [comment] 2020-04-27 14:20
@niksedk I have a question. The recalculation tool recalculates based on the max char/sec only or on the optimal as well?

**Comment by niksedk** [comment] 2020-04-27 14:45
The "Recalculate function" is based on optimal cps (a little slower for short texts, and a little faster for long texts)

**Comment by OmrSi** [comment] 2020-04-27 14:48
> @OmrSi Use bridge gap.

It's not the same, really.
It's like the Extend shortcuts, but those require you to move to the next or previous lines, while "link" would let you do it while staying on the current line.
It's not necessary, but easier. Just a suggestion.

**Comment by Andrebavila** [comment] 2020-04-27 15:45
I cannot read this. The translation is cutted.
And the line "Comportamento de divisão" is taking space from the line beside it.
Could it be fixed? Thanks!
Language: Brazilian Portuguese.

![Subtitle](https://user-images.githubusercontent.com/64425752/80391063-9fb8c080-8883-11ea-8662-3b7610bba7eb.jpg)

**Comment by moob158** [comment] 2020-04-27 16:57
@**Andrebavila** already fixed, try the last beta

@**Flitskikker**  could you add **detect and uncheck in Bold Tags**

**Comment by Flitskikker** [comment] 2020-04-27 17:00
@moob158 
What would the bold tags be used for?
I must say, as a professional subtitler, I have never seen bold tags officially supported.

**Comment by moob158** [comment] 2020-04-27 17:07
@Flitskikker 

bold tags in portuguese is used for names of places, stores, signals, etc... everything shown on the screen for translation, well not everything ;)

and can you add to uncheck lines in uppercase?

**Comment by Flitskikker** [comment] 2020-04-27 17:09
@moob158 
Ah okay. I can add a setting for bold tags, but that would require new updates in the language file...

An option for uppercase is already available.

**Comment by moob158** [comment] 2020-04-27 17:10
@Flitskikker  yes but not work

see
![Capturar](https://user-images.githubusercontent.com/60049180/80400159-503db900-88b2-11ea-9152-85ab2f006614.PNG)

**Comment by Flitskikker** [comment] 2020-04-27 17:11
@moob158 
Could you attach the file?

**Comment by niksedk** [comment] 2020-04-27 17:12
Sorry, no language file updates atm.

**Comment by moob158** [comment] 2020-04-27 17:15
here is it
[2.zip](https://github.com/SubtitleEdit/subtitleedit/files/4541092/2.zip)

**Comment by moob158** [comment] 2020-04-27 17:20
@niksedk 

here is the pt_pt language file update until last git.
[pt-PT.zip](https://github.com/SubtitleEdit/subtitleedit/files/4541113/pt-PT.zip)

**Comment by Flitskikker** [comment] 2020-04-27 17:21
@moob158 
It works fine here:

![image](https://user-images.githubusercontent.com/3516155/80401074-09ed5780-88bc-11ea-8f67-ba01dc4a94f6.png)

These lines are unchecked by default because they are uppercase.
They will not be hidden, because the COULD BE continuation sentences. Then you can check them.

If screen texts are in bold AND uppercase, then they are already detected and unchecked.

@niksedk So, no language file update needed. :)

**Comment by moob158** [comment] 2020-04-27 17:24
@Flitskikker  oh...

I thought I didn't show up, my mistake, sorry and ok :)

**Comment by niksedk** [comment] 2020-04-27 17:27
@moob158: thx for the updated :)
Committed in ccc961bda136523c5a683d36091b46599da01abc
Beta link: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.14/SubtitleEditBeta.zip

**Comment by niksedk** [comment] 2020-04-27 17:29
@Andrebavila: The text "Comportamento de divisão" needs to be shorter...

**Comment by moob158** [comment] 2020-04-27 17:33
@niksedk: thanks ;)

just one think, in portuguese the ellipsis "3 dots" in begin of line follows by space like this: "... bla bla bla"
it is possible to add the rule for this in portuguese?

**Comment by moob158** [comment] 2020-04-27 18:41
@Flitskikker: What is the options for continuation **not replace the comma**?

I tested them all and continues to replace the comma

![Capturar](https://user-images.githubusercontent.com/60049180/80408399-04454100-88bf-11ea-97eb-0ea6ff268d2e.PNG)

**Comment by Flitskikker** [comment] 2020-04-27 19:16
@moob158 
Currently there is no option to add a space before the dots.
Also, a comma is always seen as a continuation, so it will be replaced by dots (or a dash, depending on the setting).
These are hardcoded profiles to make it managable/easier for a first version.

However, internally, I took future customization into account, so for the next version, I can add a "Custom..." option that will allow users to customize everything in detail.

I already designed the UI in the beginning, before dropping it as it would get too complicated for a first version:

![image](https://user-images.githubusercontent.com/3516155/80411280-3a3cf200-88cc-11ea-824d-abbeb56b8f20.png)

But seen there is a demand for further customization, and now everything works well for a first version, I'm planning on adding this as an improvement for the next version.

There will probably be more feedback, so I can't process that too.

**Comment by moob158** [comment] 2020-04-27 19:24
@Flitskikker: customization is the way ;)

my suggestions:

- not replace others continuation styles (comma) etc...
- not remove the dots "ellipsis" in the end of line if exist
- add space after 3 dots in begin of lin for portuguese language

ok, I will wait... thanks for your hardwork ;)

**Comment by niksedk** [comment] 2020-04-27 19:26
Yes, there's should probably be a "Disabled/Ignore" mode for "Continuation style"... I initially thought that "None" did that...

**Comment by OmrSi** [comment] 2020-04-27 19:27
Well, does it matter?
It doesn't have an effect if it's not activated in FCE, right?

**Comment by moob158** [comment] 2020-04-27 19:36
in short, It is only necessary **one** continuation style

add continuation style only to **lines end without punctuation and to begin next line**

no need more

**Comment by Flitskikker** [comment] 2020-04-27 19:47
@moob158 
> in short, It is only necessary one continuation style, dots or dash
> only to lines end without punctuation and to begin of next line

In Dutch subtitles (and most other languages), the comma will always be replaced.

@OmrSi 
> Well, does it matter?
> It doesn't have an effect if it's not activated in FCE, right?

Yes, that's the idea.

**Comment by Flitskikker** [comment] 2020-04-27 19:50
@moob158 @niksedk 
Quick fix for Portuguese: #4155 
It should do what you want. It will now ignore sentences ending with comma. Plus spaces will be added after the dots of the prefix.

Of course it will be added to the UI properly in the next version.
Just so you can use this version for Portuguese..

**Comment by Flitskikker** [comment] 2020-04-27 19:52
> Yes, there's should probably be a "Disabled/Ignore" mode for "Continuation style"... I initially thought that "None" did that...

> Well, does it matter?
> It doesn't have an effect if it's not activated in FCE, right?

@niksedk 
Could you uncheck "Fix continuation style" by default in the FCE dialog when the continuation style is set to "None" (and maybe the other "None, but ..." options)? Then it will be ignored by default when running FCE.

**Comment by moob158** [comment] 2020-04-27 19:55
@Flitskikker: not in Portugues, pt/pt-br, not in English, not in Spanish, not in Italian, etc...

I don’t say in all languages but in those I know and are some, not a replace the comma

**Comment by Lero91** [comment] 2020-04-27 20:03
The English translation contains some Greek. I just noticed.
![Ελληνικά](https://user-images.githubusercontent.com/63797709/80415476-47151200-88db-11ea-93be-9161451df83a.jpg)

**Comment by Flitskikker** [comment] 2020-04-27 20:04
@moob158 
English subtitles only have dots when there is a long pause.

Setting: None, but dots for pauses

If there is a short pause, there will be no dots added, and the commas will not be replaced.
If there is a long pause, there will be dots added, and the comma will be replaced if present.

![image](https://user-images.githubusercontent.com/3516155/80415564-01ece200-88d3-11ea-9815-c864319106f6.png)

**Comment by moob158** [comment] 2020-04-27 20:07
@Flitskikker  in Portuguese too, dots its only for long pause

short pause is the comma like in english, spanish italian...

**Comment by Flitskikker** [comment] 2020-04-27 20:29
@moob158 
This should already work like this when using the setting "None, dots for pauses" ("Nenhum, reticências para pausas")

**Comment by moob158** [comment] 2020-04-27 21:43
@Flitskikker: is better thanks

but continues removing existing "dots at end of line"

![Capturar](https://user-images.githubusercontent.com/60049180/80423639-4464ed80-88d8-11ea-8cdb-3b9bdee97559.PNG)

**Comment by Flitskikker** [comment] 2020-04-27 22:13
@moob158 
There is only 167 ms between these lines, so it is detected as a short pause, so normally there would be no dots. Thus, it is suggesting to remove them.

If there are dots and it's a long pause, then it will not remove the dots.

In this case, it's short pauses but there were already dots, probably hesitations. But the software cannot distinguish a normal continuation vs. a hesitation. You can verify if all the fixes are correct and uncheck the ones that are not needed (for example in these cases -- it's only 8 lines to check). Not everything can be 100% automatic unfortunately.

I can look into adding an option "Don't remove existing dots if the subtitle doesn't use dots by default", but that is not something I can hotfix, so that would be for the next version.

So, for now, please verify the suggested fixes and uncheck the ones you don't want. I hope that's not too much trouble.

**Comment by moob158** [comment] 2020-04-27 22:26
@Flitskikker: I understand what you say, but this is a subtilte the viewer only see line by line

it's more a matter of style when subtitling than practicing

the viewer rarely thinks whether it’s a long or short pause through reading the subtitle line by line

**Comment by Flitskikker** [comment] 2020-04-28 10:04
@moob158 
What did you mean by your last sentence? (Can't see it anymore)

**Comment by Flitskikker** [comment] 2020-04-28 14:26
@niksedk 
A bug report from another user (whom I've asked to test the new beta):

When the dialog style is set to "Dash second line (with/without space)", and the subtitle has a short dialog, then the option "Remove line breaks from short lines (all except dialogs)" aka "Merge short line (all except dialogs)" will still remove line breaks from dialogs.

When the option "Fix dialogs on one line" is also checked, the list will available fixes will not change after clicking Apply (as the one action will undo the other's).

![image](https://user-images.githubusercontent.com/3516155/80499156-e9c9a100-896c-11ea-8fc5-aea2bb8a0d89.png)

**Comment by OmrSi** [comment] 2020-04-29 01:23
@niksedk The whole name isn't showing up in the title bar when opening from a video file:
![image](https://user-images.githubusercontent.com/20923700/80552985-eb2cb500-89d0-11ea-91a6-1f804db8203e.png)
It should be: `6.Underground.2019.1080p.10bit.WEBRip.6CH.x265.HEVC-PSA.srt`
It shows up for a sec when you open it then gets cut.
It shows up full when you save the file:
![image](https://user-images.githubusercontent.com/20923700/80553044-26c77f00-89d1-11ea-8d2b-adc1397ea0c0.png)

**Comment by niksedk** [comment] 2020-04-29 10:57
Beta updated with latest changes: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.14/SubtitleEditBeta.zip

**Comment by Lero91** [comment] 2020-04-29 18:06
Last translation updates.
[Translation.zip](https://github.com/SubtitleEdit/subtitleedit/files/4553447/Translation.zip)

Can you take a look at this? When the language is set to English, this choose color window appears in Greek.

> The English translation contains some Greek. I just noticed.
> ![Ελληνικά](https://user-images.githubusercontent.com/63797709/80415476-47151200-88db-11ea-93be-9161451df83a.jpg)

**Comment by xylographe** [comment] 2020-04-30 08:18
@Lero91 
This colour chooser is implemented in the `System.Windows.Forms.ColorDialog` class. As a part of .Net it uses the .Net UI language (`System.Globalization.CultureInfo.CurrentUICulture`) instead of the SubtitleEdit language setting.

**Comment by Lero91** [comment] 2020-04-30 08:59
> @Lero91
> This colour chooser is implemented in the `System.Windows.Forms.ColorDialog` class. As a part of .Net it uses the .Net UI language (`System.Globalization.CultureInfo.CurrentUICulture`) instead of the SubtitleEdit language setting.
OK, thanks for the help.

**Closed** 2020-05-01 08:27 UTC

**Comment by OmrSi** [comment] 2020-05-04 23:26
@niksedk It's shown even before you make any change in the latest beta:
![image](https://user-images.githubusercontent.com/20923700/81022989-be1c4e80-8e77-11ea-8a78-ea46fe5411a3.png)
