### ISSUE TITLE
[Feature Request] Option to close translated subtitle

### ISSUE THREAD

**Issue by zcraber** [SubtitleEdit/subtitleedit#6450] opened 2022-11-23 07:37 UTC
After translating the subtitle using auto-translate and saving it, an option to **Close translated subtitle** in the **File** menu will be handy in cases where the user wants to translate sub into multiple languages.

**Comment by LeonCheung** [comment] 2022-12-10 08:42
True, this is really nice to have, or maybe better call it "**Quit translation mode**" because literally the project file you are working on is the translation, and closing it means you close the current project, so I think **Quit** would be better.

**Comment by zcraber** [comment] 2022-12-10 09:00
There

> True, this is really nice to have, or maybe better call it "**Quit translation mode**" because literally the project file you are working on is the translation, and closing it means you close the current project, so I think **Quit** would be better.

There is an option called **Close original subtitle**. That's the reason I suggested the word **Close**.

![image](https://user-images.githubusercontent.com/61133303/206842258-7b1afd08-9621-4d8b-98a3-2752ed19153e.png)

**Comment by LeonCheung** [comment] 2022-12-10 09:12
Makes sense too. :) Or "**New (keep original subtitle)**"

**Comment by niksedk** [comment] 2022-12-10 09:17
He, `Close translated subtitle` might be best. 
It's probably different what people does next... auto translate (google/deepl/?), or just start with a blank, right?

**Comment by zcraber** [comment] 2022-12-10 09:26
> He, `Close translated subtitle` might be best. It's probably different what people does next... auto translate (google/deepl/?), or just start with a blank, right?

My intention would be to auto-translate the **original** to another language.

**Comment by LeonCheung** [comment] 2022-12-10 09:27
Yes, sometimes. Or another case would be misloading. For example, yesterday we did the translation for the file. Today when I drag and drop to open either of the two files, SE will load both automatically in translation mode, but I just wanna edit one of them... it does happen, not sure if it's by design.

**Comment by niksedk** [comment] 2022-12-10 10:40
OK, does this work for you: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.10/SubtitleEditBeta.zip ?

![image](https://user-images.githubusercontent.com/1261331/206851025-bf1e97f6-6cd7-4a74-8022-58282ad91306.png)

**Comment by LeonCheung** [comment] 2022-12-10 11:02
Nice. All cool here. :)

**Comment by zcraber** [comment] 2022-12-10 11:09
Awesome. Works perfect! Thank you.

**Comment by niksedk** [comment] 2022-12-10 12:18
thx for testing :)

**Closed by niksedk** 2022-12-10 12:18 UTC
