### ISSUE TITLE
Auto Subtitle generation

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [SubtitleEdit/subtitleedit#2796] opened 2018-02-28 23:18 UTC
Can SE auto-generate the subtile from the sound wave?
If not, why don't you add this feature using Google Web Speech API ?
For simplicity, you can make use of this utility:
https://github.com/agermanidis/autosub

**Comment by gabriellluz** [comment] 2018-03-01 11:40
He's already implementing that function through CMU Spinx. As for your issue, this is a duplicate of https://github.com/SubtitleEdit/subtitleedit/issues/2150

**Closed** 2018-03-04 13:28 UTC
