### ISSUE TITLE
503 Service Unavailable

### ISSUE THREAD

**Issue by XhstormR** [SubtitleEdit/subtitleedit#8295] opened 2024-05-02 16:53 UTC
https://www.nikse.dk/SubtitleEdit/Help
503 Service Unavailable
Thu May  2 19:51:52 +03 2024
<img width="567" alt="image" src="https://github.com/SubtitleEdit/subtitleedit/assets/10527522/25524f4b-6266-4b8a-987d-e6b77c337831">

**Comment by niksedk** [comment] 2024-05-02 17:54
Dupe of https://github.com/SubtitleEdit/subtitleedit/discussions/8267

**Closed by niksedk** 2024-05-02 17:54 UTC
