### ISSUE TITLE
Extract images from video

### ISSUE THREAD

**Issue by Wernouxe** [SubtitleEdit/subtitleedit#8175] opened 2024-04-13 05:31 UTC
Hi, I have a suggestion that I think might be of interest to many! (Especially if you use Tesseract!)

Extract subtitled frames from a video
This function captures each frame of the video containing a subtitle, renaming the frames with the timecode.
(So it's possible to do this for several videos).

**Comment by niksedk** [comment] 2024-04-13 07:45
Duplicate of https://github.com/SubtitleEdit/subtitleedit/issues/340 I think... ?

**Closed** 2024-04-13 07:45 UTC

**Comment by Wernouxe** [comment] 2024-04-13 09:14
Ah yes sorry!
