### ISSUE TITLE
Whisper models appear to be missing in new SubtitleEdit install, DL's of models destroy existing models

### ISSUE THREAD

**Issue by LastJasonNext** [SubtitleEdit/subtitleedit#7080] opened 2023-07-08 23:12 UTC
### Discussed in https://github.com/SubtitleEdit/subtitleedit/discussions/7079

<div type='discussions-op-text'>

<sup>Originally posted by **LastJasonNext** July  8, 2023</sup>
I saved the 3 models that hadn't been destroyed (by attempting a fresh Download in the Whisper dialog), did a complete uninstall then installed SubtitleEdit 3.6.13. After installation, the Whisper dialog asked to DL ffmpeg and cpp run files, which appear successful. No model options are preloaded into the model dropdown menu, and a Download selection of a model results in the loading of a 1K empty model file. So a complete reinstall of SubtitleEdit 3.6.13 will not resurrect the destroyed base.en.bin.

As another avenue while searching for replacement(s), I asked CharGPT 4.0 for a downloadable address for the .bin models. It was happy to give me one at Huggingface, however that folder appears to be empty. We discussed the difference between .pt models (reformed for python usage) and the original .bin models, so I'm fairly sure GPT 4.0 was accurate with the link. Perhaps someone could try that as well (I used Bing's).

-J

</div>

**Comment by niksedk** [comment] 2023-07-09 05:18
The links has changed: https://github.com/SubtitleEdit/subtitleedit/commit/cf429947956e60d9f3236b9c2153e8bdcea503b1

Fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip

Duplicate of:
https://github.com/SubtitleEdit/subtitleedit/issues/7060
https://github.com/SubtitleEdit/subtitleedit/issues/7074

**Comment by LastJasonNext** [comment] 2023-07-10 04:38
Thank you, Nikolaj! 

I did end up using the huggingface addresses posted in permission errors
(due to needed folders in Roaming), to DL the .bin files (removing the
ggml- prefixes), placing them in the 3.6.13 Roaming/Subtitle
Edit/Whisper/Models folder, and running the 3.6.13 release successfully.


Those ggml- .bin links were what I was trying to find on huggingface
with no success. Seeing them in the beta's error notifications was a
pleasant surprise. 

Noticeable improvements in the models. Wow. 

-J 

On 2023-07-08 22:18, Nikolaj Olsson wrote:

> The links has changed: cf42994 [1] 
> 
> Fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip 
> 
> Duplicate of:
> #7060 [2]
> #7074 [3] 
> 
> --
> Reply to this email directly, view it on GitHub [4], or unsubscribe [5].
> You are receiving this because you authored the thread.Message ID: ***@***.***>
 

Links:
------
[1]
https://github.com/SubtitleEdit/subtitleedit/commit/cf429947956e60d9f3236b9c2153e8bdcea503b1
[2] https://github.com/SubtitleEdit/subtitleedit/issues/7060
[3] https://github.com/SubtitleEdit/subtitleedit/issues/7074
[4]
https://github.com/SubtitleEdit/subtitleedit/issues/7080#issuecomment-1627608566
[5]

**Closed** 2023-08-05 09:20 UTC
