### ISSUE TITLE
Subtitle Edit 3.5.13 tesseract returned with code -1073741795 error

### ISSUE THREAD

**Issue by ashvolcano99** [SubtitleEdit/subtitleedit#3937] opened 2020-01-21 11:15 UTC
I'm Getting this Issue when I start OCR on an Arabic Idx Sub file With tesseract 4.1.1

![بدون عنوان222](https://user-images.githubusercontent.com/60135983/72800082-93571300-3c57-11ea-8eba-f0fbbbc00ad9.jpg)

And After the First Issue this other Issue Appears " Tesseract command-line OCR engine has stopped working"

![بدون عنوان](https://user-images.githubusercontent.com/60135983/72800080-9225e600-3c57-11ea-8763-57045b42d778.jpg)

But when i use Subtitle Edit 3.5.11 With tesseract 4.1.0 there's No Problem at all .. Plz Help me to Solve this Issue 

Best Regards ☺

**Comment by xylographe** [comment] 2020-01-21 12:37
Either use _Engine mode_ "Original Tesseract only", or look at https://github.com/SubtitleEdit/subtitleedit/issues/3933#issuecomment-576618240,

**Comment by niksedk** [comment] 2020-01-21 14:18
Duplicate of #3933

**Closed by niksedk** 2020-01-21 14:18 UTC
