### ISSUE TITLE
Adjustment to Fix first letter to uppercase after paragraph

### ISSUE THREAD

**Issue by Boulder08** [SubtitleEdit/subtitleedit#4073] opened 2020-03-30 16:01 UTC
These kinds of lines trigger the fix incorrectly. Probably two or more dots will do the same there.

```
177
00:07:45,793 --> 00:07:47,327
That's what
I needed it for--

178
00:07:47,378 --> 00:07:49,930
to process this bomb
that you dropped on me.
```

**Comment by niksedk** [comment] 2020-03-30 17:39
Hm, I disagree with this one... I think two hyphens indicate abrupt interruptions - and a line ending.

**Comment by borifax** [comment] 2020-04-18 11:11
These two characters often appear in subtitles. I always have to replace them with an ellipsis (...).

**Comment by OmrSi** [comment] 2020-06-14 16:11
Duplicate of https://github.com/SubtitleEdit/subtitleedit/issues/360

**Closed** 2020-06-14 17:46 UTC
