### ISSUE TITLE
[Feature Request] Custom format creation

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#4221] opened 2020-06-05 14:42 UTC
Hi.
So, as you could see from https://github.com/SubtitleEdit/subtitleedit/issues/4218, there are occasionally unusual formats that show up in orders we get from clients, and there's really no rhyme or reason to them. I work with ELR all the time, so I've asked you to add the ELR print format, but there's also this, for instance:
[DSAL-312H_2219443_scripts.txt](https://github.com/SubtitleEdit/subtitleedit/files/4736622/DSAL-312H_2219443_scripts.txt)
Which is similar to the format from the previous issue, in that it only has the starting time code, and which SE currently doesn't parse correctly. I also haven't seen it before or since.
So, my suggestion is to add a custom format creator. Where if it's something on the level of SRT, that is, mostly text without a lot of additional data about the position of the subtitle on the screen, etc., a user could just create their own custom format, and we wouldn't have to bother you with it.
The most rudimentary version I imagine would have, like, placeholders for (start time), (end time), (subtitle text), what the breaking character is, does it use frames or milliseconds, does it have an opening line with the format description (like PE2), and so on. And you could have a sample subtitle open in the window with each element highlighted, to see that everything's been entered correctly and that SE recognizes it.

**Comment by OmrSi** [comment] 2020-06-05 22:12
Duplicate of https://github.com/SubtitleEdit/subtitleedit/issues/2626?

**Comment by darnn** [comment] 2020-06-05 22:23
I mean, I think mine is more general, but I suppose a case could be made.

**Comment by LeonCheung** [comment] 2020-06-08 16:31
For this particular format, actually you can copy/paste all texts in Source view, then switch back to List view. Ta-da...
But I agree that it would be cool to have a tool to define parsing rules for any users so that nikse would save lots of time and energy to support countless new formats for users. 
Say, Maybe we could develop 
And it could be imported and exported too as templates (similar to what the Multiple Replace tool did), so that users can help each other by sharing the files.  :)

**Comment by LeonCheung** [comment] 2020-06-08 17:52
A very basic idea could be:

![idea](https://user-images.githubusercontent.com/494788/84063488-b3635500-a9f3-11ea-9f3a-9df35a62ced3.png)


Everything could be done by simply selecting and clicking. I hope... 😄

**Comment by darnn** [comment] 2020-06-08 22:05
Ah, interesting, I didn't know that about source view! Of course, I was sent this as a txt file with no description of what format it was, as befits the level of professionalism of the people I work with. Also, that mockup looks great!

**Closed** 2022-08-28 17:59 UTC
