### ISSUE TITLE
Auto-translate problems with Deepl 

### ISSUE THREAD

**Issue by De-rota** [SubtitleEdit/subtitleedit#8882] opened 2024-10-04 18:24 UTC
I can't use the automatic translator with the Deepl API. It doesn't translate any of the text, it only leaves the formatting codes.

I really need help with this, please!

Thanks!

![Screenshot_1](https://github.com/user-attachments/assets/79f41752-02b0-4282-b9e4-6e9f922e86d8)

**Comment by niksedk** [comment] 2024-10-12 07:31
> ...When I click "Translate", I get this error message...

Thx, the crash should now be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.8/SubtitleEditBeta.zip

**Closed** 2024-10-12 07:31 UTC

**Comment by geeky-gurl** [comment] 2024-10-14 00:17
@niksedk Thank you very much for the quick reaction. 
Just FYI, I didn't mention I was using a Windows 8.1 computer. I think the problem is specific to 8.1 because I tried is on Win 10 and Win 11, and it works fine.
