### ISSUE TITLE
Playback always across the end point in Waveform window

### ISSUE THREAD

**Issue by huangguan0217** [SubtitleEdit/subtitleedit#2962] opened 2018-06-28 03:31 UTC
(1) In Waveform window, Playback always across the end point when I press F5 to play the selected sections, after playing was done, **the playback position will stop at short distance but very close the end point**, it looks kind of annoy.

Is there any settings could adjusting some specific value to solve above issue? Many thanks.

(2) If I enable undock mode, except Waveform window, which couldn't return to the last position when I was re-open SubtitleEdit, so I need resizing its window every time and drag it to the satisfaction position.

Actually it doesn't affect any of the functionality, just little bit of inconvenience, I really love SubtitleEdit, but I think those issue could be fixed in the next version.

Video File Format: MKV
The type of System: Windows 10
The currently version: 3.5.6 (not beta version)

**Comment by LeonCheung** [comment] 2018-06-30 06:23
都不算大事，要啥自行车 :rofl: 有点好奇你想要的布局是什么样的，方便截个图？

**Comment by LeonCheung** [comment] 2018-07-12 02:32
@huangguan0217 For the first point, I think I've reported it 3 years ago at #706. Anyway, still waiting for the offical explanation. I'll close it if it is hard to tackle.

**Comment by niksedk** [comment] 2020-01-07 05:54
Closed as duplicate of  #706

**Closed by niksedk** 2020-01-07 05:54 UTC
