### ISSUE TITLE
SubtitleEdit 4.0.1 trojan "Trojan:Win32/Bearfoos.A!ml" detected by Windows Defender 

### ISSUE THREAD

**Issue by mikaljan** [SubtitleEdit/subtitleedit#7421] opened 2023-09-19 15:20 UTC
SubtitleEdit 4.0.1 trojan "Trojan:Win32/Bearfoos.A!ml" detected by Windows Defender 
setup file was downloaded directly from github:
SubtitleEdit-4.0.1-Setup.exe

After installation, the file: file: C:\Program Files\Subtitle Edit\SubtitleEdit.exe is reported by Windows Defender as infected trojan.

Note: this trojan was not detected on SubtitleEdit 4.0.0

**Comment by niksedk** [comment] 2023-09-19 15:37
Dupe of https://github.com/SubtitleEdit/subtitleedit/discussions/7415

**Closed** 2023-09-19 15:37 UTC

**Comment by niksedk** [comment] 2023-09-20 05:15
Noi flogs on virus total now:

Portable: https://www.virustotal.com/gui/file/3729606b10a6cc47bc72c6ff1570931eaf1072974f979137ea6239ed6edada48
Installer: https://www.virustotal.com/gui/file/124a9dd46e041ed5fc05dc6341cf9ecc25ed5c7fa0b2512e42c20ff53240f005
