### ISSUE TITLE
High DPI Support

### ISSUE THREAD

**Issue by stax76** [SubtitleEdit/subtitleedit#2434] opened 2017-06-10 09:05 UTC
In case your screen is Full HD and you have good enough eyesight to use 96 DPI you might not know that your app looks poor on systems with 144 or more DPI. Some reasons people use high DPI is they have large 4K screens and/or poor eyesight, in my case both. I can help you if you have problems or questions regarding High DPI win forms development.

**Comment by evolfox** [comment] 2017-11-09 11:44
Hello.

I use a 4K screen and the preview video is not displayed correctly. https://i.imgur.com/pC0UV5f.jpg

**Comment by nyuszika7h** [comment] 2018-07-25 19:51
There's still no high DPI support, this would be nice.

**Comment by niksedk** [comment] 2018-08-01 14:49
Sorry, I don't know how to test this... any help is welcome. Also, I'm not sure what the problem is.

**Comment by nyuszika7h** [comment] 2018-08-02 13:42
The interface looks blurry on my 1080p screen with 125% scaling:

![Screenshot of Subtitle Edit with scaling performed by system](https://user-images.githubusercontent.com/482367/43587417-7bb0fad4-966a-11e8-8c8b-bc5cc275a7b2.png)

If I enable "Override high DPI scaling behavior. Scaling performed by: Application", some spacing is not exactly right:

![Screenshot of Subtitle Edit with scaling performed by application](https://user-images.githubusercontent.com/482367/43587507-ad5566b0-966a-11e8-8b28-56d07d5e6316.png)

**Comment by PannenkoekenNL** [comment] 2019-03-01 19:29
> Sorry, I don't know how to test this... any help is welcome. Also, I'm not sure what the problem is.
You can test it by setting the DPI in Windows higher. Setting > Display > Change the size of text, apps, and other items.

![test](https://user-images.githubusercontent.com/16383282/53661486-b2743d00-3c60-11e9-84a3-bb76242bc86b.png)

The problems is that Subtitle Edit looks blurry when having a higher DPI, a higher DPI is needed when using high resolution tablets/notebooks, 4K monitors etc. Or just when you've bad eye sight.

**Comment by dabisu** [comment] 2021-05-17 06:36
I see this bug report is open from 2017. Most of applications are DPI aware and scale properly. Any chance it will be fixed in SE? I really like SE, but blurry fonts... Nowadays a growing number of users are buying bigger monitors, and if you're don't have good sight it's a must to set the dpi scaling to 125% or more.

**Comment by lavadrop** [comment] 2021-12-14 04:54
This is still a thing and it's really impacting my use of the program. For example, the configuration menus are almost unreadable in Linux at 200% scale using mono.

**Comment by dabisu** [comment] 2021-12-17 22:45
This workaround works for me: in the properties menu for SubtitleEdit.exe, check the "Override High DPI scaling behavior" option under "Change high DPI settings".

**Closed** 2022-08-28 17:27 UTC

**Comment by dabisu** [comment] 2022-08-28 22:23
Just checked 3.6.7 and the high dpi problem is still present, so it doesn't seem completed.

**Comment by niksedk** [comment] 2022-08-29 03:57
This issue has timed out... I don't really know how to solve this. A PR is still welcome.

**Comment by dabisu** [comment] 2022-08-29 14:54
Hi Nikolaj. It's ok, I just wanted to point out that it still present. I'd like to help, but I'm more of a linux programmer, so I completely clueless about how Windows manages this.

**Comment by AdventurerRussia** [comment] 2023-03-11 06:34
@niksedk 

I solved it in the exe properties in the explorer, there is a punto in the compatibility tab - change the high dpi parameters, there is a jackdaw at the bottom - redefine the mastabbing mode, click the jackdaw and select applications
![image](https://user-images.githubusercontent.com/14019010/224469248-6fc524cb-f22e-40d8-bcac-c2b60f0d9690.png)

**Comment by AdventurerRussia** [comment] 2023-03-11 06:35
this removed the blurring of the app.

**Comment by Hsclone** [comment] 2024-10-27 08:29
After selecting "Change high DPI settings" to "Application", the text indeed became clearer, however, the setting messed up the layout of the app, some text couldn't show, some buttons were way too small, the elements in  "Options-Settings"page were all crammed together.  So the problem was still unsolved.

**Comment by eugenesvk** [comment] 2025-05-03 15:19
You could check this version https://github.com/SubtitleEdit/subtitleedit/pull/9637 (if you can't build, try [Windows downloads from here](https://github.com/eugenesvk/subtitleedit/releases/tag/4.0.13a)), which solves a lot of the DPI scaling issues for me (and doesn't require manually setting compatibility settings for the exe file)

It's still not perfect DPI-aware layout, but much better than the current version
