### ISSUE TITLE
3.5.18 beta 683: Find next doesn't advance to next occurrence intermittently

### ISSUE THREAD

**Issue by GrampaWildWilly** [SubtitleEdit/subtitleedit#4749] opened 2021-01-23 01:21 UTC
I don't know if this is a quirk of the particular vtt file I was looking at (which I have attached, with the file extension changed from vtt to txt to satisfy the restriction here on github) or a quirk of the particular character strings I was searching for ("and" and "-").  But when I hit F3 to find the next occurrence, SE did not always advance to the next occurrence, even though there were many such later occurrences.  F3 would cause SE to just sit there on the current caption.  When I manually advanced one caption & hit F3 again, SE then correctly advanced to the next occurrence.  But not always.  Sometimes, F3 would find the next occurrence, sometimes for several instances in a row.  But then it would get stuck on an occurrence later in the file again & I would have to kick it to the next caption to get the search to continue properly.  At end-of-file, it did wrap around to find the first occurrence again, which is correct behavior.  The previous beta I had been using was 566 & it didn't have this problem.  So, something changed between then & now to introduce the problem.

[Tosca Video 19850327.txt](https://github.com/SubtitleEdit/subtitleedit/files/5859384/Tosca.Video.19850327.txt)

**Comment by OmrSi** [comment] 2021-01-23 02:21
@niksedk I think this is happening in the RichTextBox because of the change in the index done in the setter and getter, I haven't looked into how Find is coded so I don't think I can fix this, hope you can take a look.

**Comment by niksedk** [comment] 2021-01-23 11:23
OK, should be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.18/SubtitleEditBeta.zip
Fixed an issue with the "syntax-color textbox" - let me know how it works for you!

**Comment by GrampaWildWilly** [comment] 2021-01-23 12:39
Well . . .  The F3 issue seems to be fixed.  But there's something else going on.  And since the something else has to do with the text color in the text box, and since you say this had something to do with "syntax-color textbox," I'm going to put this comment here rather than open a new issue.

What I am seeing is that the text in the text box is a rather light blue.  This is despite the fact that in the settings dialog (just noticing you've changed the settings dialog -- I like the change) on the Font page, I have the subtitle color set to black.  I experimented a bit with hitting MB2 in the text box & picking Color... from the popup context menu.  In the color selector, black is selected.  I clicked another color then immediately black again & then OK.  I thought it would change the font color in SE but it looks like it puts a tag into the caption for directing the video player to use black color when displaying the caption during video playback.  Well, that's not at all what I wanted so I did Ctrl-z to back that out.  That made the text in the context box change from blue to black, which is what I was trying to do, but I'm thinking this is just an accident that it has this effect.

Scrolling through the captions in that vtt left the text in the text box black.  But when I opened a different vtt, the blue text came back again.

Here's something else I noticed very much by accident.  I was scrolling through captions after doing my trick to turn the text black when I came across a caption that just accidentally happened to be bracketed with &lt;i&gt; &lt;/i&gt;, which makes the caption display in the video player in italics.  The start & end tags were in blue & the text between them was black.  It so happened that several consecutive captions were italicized like this, & they all showed the HTML tags in blue & the text in black.  I think this is fine, although I might choose a different color if I start getting caption files with a lot of embedded HTML tags, which I normally do not.  I believe I saw where I can change this color on the same settings page for Fonts I mentioned above.

But here's the weird thing.  When I cycled forward from the last in the series of italicized captions to one that didn't have the italics tags, the blue text reappeared.  It seems like if you've got a caption with HTML tags in it, the next caption without tags goes back to blue.

I'll attach that caption file for you to test with.  I really wish this site would accept files with extension vtt.  It's rather bothersome that I have to make a copy of any caption file I want to attach & rename it from vtt to txt.

[Faust Video 20111210.txt](https://github.com/SubtitleEdit/subtitleedit/files/5860180/Faust.Video.20111210.txt)

**Comment by niksedk** [comment] 2021-01-23 13:48
Thx for testing :)
The subtitle font color/back-color should now work without re-starting: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.18/SubtitleEditBeta.zip

I cannot re-create lines without italic being colored with the italic color - what did you do? And can you re-create it?

**Comment by GrampaWildWilly** [comment] 2021-01-23 17:13
With beta 694, I opened the Faust captions.  The first 20 captions are just ordinary captions containing no HTML tags.  I scrolled through those in the list view using DownArrow (focus in the caption list, not the text box) & the text box showed black on white, my color choices in SE settings.  Caption #21 is the first one with the italics tags.  Scrolling into it made it display with the HTML tags in blue surrounding text in black.  Captions 21-25 all displayed like that.  I scrolled through them continuing to simply type DownArrow with focus in the caption list, not the text box.  As soon as I scrolled to caption #26, the text box started displaying the text in blue.  Continuing to scroll anywhere in the file still showed text in blue, including now captions #1-20, which had been black.  The 5 italicized captions continued to show the tags in blue & the text in black.  There's several sequences of italicized captions scattered throughout the file.  They all showed blue tags surrounding black text.  I could recreate this at will by using my little trick of popping up the context menu in the text box of any caption with no HTML tags, selecting Color..., then closing the dialog.  This reverts non-tag captions to black text.  But displaying any italicized caption changes the color of non-tag captions back to blue.

More to come . . .  I'm now going to download the latest beta.  Stand by . . .

**Comment by GrampaWildWilly** [comment] 2021-01-23 18:07
I now have beta 696 & there is no change in this behavior.  I started SE on the Tosca captions I posted first.  The text in the text box was black.  There are no captions in that file that have embedded HTML tags.  The text remained black no matter what I did.

I switched to the Faust captions without closing SE.  The captions with no embedded HTML tags were black.  As soon as I displayed any caption that had the italics tags, all non-tag captions went blue.  Switching from Faust with blue text to Tosca made the text display in blue in Tosca.  Separately, while I was seeing blue text in Faust, I closed & reopened Faust.  The non-tag text reverted to black.  But once again, displaying any italicized caption made the non-tag captions go blue.

If I understand the settings correctly, on the Font page, if you have "Use syntax coloring" checked, the HTML button below that chooses the color in which to display HTML tags (like italics) embedded in captions.  This is a nice feature, in my opinion.  But it seems like SE gets confused when it actually uses that color setting.  Switching from a black caption to a caption with tags should continue to display the text in black while showing the embedded HTML tags in the color specified in the settings.  This appears to occur.  But trouble starts when SE goes back from a caption with tags to a caption without tags.  It doesn't go back to using the original color scheme.  It seems to be treating all the text as if it were an HTML tag.  The entirety of the text in the text box is being displayed in the HTML tag color.  This appears to be a leftover from displaying a caption with tags.  Once non-tag captions go blue, tag captions do continue to be displayed as black surrounded by blue.  But non-tag captions stay blue until I either do my trick or close & reopen SE.

**Comment by OmrSi** [comment] 2021-01-23 18:21
I am unable to reproduce this:
![Untitled Project](https://user-images.githubusercontent.com/20923700/105610491-7bf5bd00-5db8-11eb-8642-0f575aea04a1.gif)

**Comment by GrampaWildWilly** [comment] 2021-01-23 19:00
One difference I notice from what you're showing & how I've got it is that my background color is white & my text color is black.  Also, I don't know if this is significant, but I'm running with the controls detached & the MPV player displayed on my second monitor.

**Comment by OmrSi** [comment] 2021-01-23 19:05
> One difference I notice from what you're showing & how I've got it is that my background color is white & my text color is black.

I'm using the new dark mode.
Although I tried it with the light mode and with the controls undocked, still couldn't reproduce this.

Could you attach your Settings file?

**Comment by GrampaWildWilly** [comment] 2021-01-23 19:09
Again, I had to copy the file & change the extension because this site doesn't support attachments with an extension of XML.

[Settings.txt](https://github.com/SubtitleEdit/subtitleedit/files/5860890/Settings.txt)

**Comment by OmrSi** [comment] 2021-01-23 19:18
Sadly, I'm still unable to reproduce this.

**Comment by OmrSi** [comment] 2021-01-23 19:40
@GrampaWildWilly Can you try this? 
[SubtitleEditBeta.zip](https://github.com/SubtitleEdit/subtitleedit/files/5860932/SubtitleEditBeta.zip)

**Comment by GrampaWildWilly** [comment] 2021-01-23 19:48
Magic!  You fixed it!  Thanks bunches!

**Closed** 2021-01-23 20:32 UTC
