### ISSUE TITLE
[Feature Request] Batch Google Translate Scraping/Normal Option

### ISSUE THREAD

**Issue by orbittwz** [SubtitleEdit/subtitleedit#3233] opened 2018-12-12 20:56 UTC
Hi!
So as you already know, VASE by MohammadHamdyGhanem has this cool feature with allows batch GT translation.
It takes an input from a set folder, not recursive afaik, just the root folder and one by one it translates the contents with set languages pair in the start, and saves the files in the root folder with the appropriate suffix which already set in normal SE when you GT normally.
The ease of use with this feature will make SE very efficient and the best there is right now.
Thanks

**Comment by orbittwz** [comment] 2019-01-05 10:52
Hmm?? anyone kind enough to think about this?

**Comment by orbittwz** [comment] 2019-01-14 17:43
How is it connected to my request??

**Comment by OmrSi** [comment] 2019-01-14 17:47
This is the related one: https://github.com/SubtitleEdit/subtitleedit/issues/3124

**Comment by orbittwz** [comment] 2019-01-15 17:52
oh, it was chained from another suggestion...
OK then

**Comment by niksedk** [comment] 2019-01-19 13:14
Duplicate of #3124

**Closed by niksedk** 2019-01-19 13:14 UTC
