### ISSUE TITLE
SE 3.5.13 & Tesseract 4.1.1 OCR Bug ( -1073741795 error )

### ISSUE THREAD

**Issue by wtester7** [SubtitleEdit/subtitleedit#3933] opened 2020-01-20 15:22 UTC
Hi @niksedk,

just tested your newly released SE 3.5.13 & Tesseract 4.1.1 but it is impossible to OCR a mks file.
With SE 3.5.11 & Tesseract 4.1.0 there is no problem when OCR'ing...

Somethings wrong with Tesseract 4.1.1 in your SE 3.5.13. 
I have 7zipped the fresh portable SE 3.5.13 with the mks file "00003.mks" in the root directory so you can test the problem for yourself... 

https://www.upload.ee/files/11005579/SE3513.7z.html

Btw, this happens with other mks files too!

Thanks Nik!

**Comment by niksedk** [comment] 2020-01-20 17:09
The .mks file works fine here... what your OS and what's the problem?

**Comment by wtester7** [comment] 2020-01-20 17:32
Win10 x64 Build 1903.

**With SE 3.5.11 & Tesseract 4.1.0 there is no problem when OCR'ing...**

**With SE 3.5.13 & Tesseract 4.1.1 this problem occurs when OCR'ing:**

<a href="https://www.upload.ee/image/11006115/Tesseract_4.1.1_OCR_Error.jpg"><img src="https://www.upload.ee/thumb/11006115/Tesseract_4.1.1_OCR_Error.jpg" border="0" alt="Tesseract_4.1.1_OCR_Error.jpg" /></a>

**Comment by vivadavid** [comment] 2020-01-20 18:36
Hi,

I've tested the MKS file and I get the same error on Win 10 x64 1909. I saw the "Tesseract returned with code" message for the first time with SE 3.5.12, so it looks like it must have something to do with Tesseract 4.1.1.

**Comment by wtester7** [comment] 2020-01-20 19:01
This is a serious problem because I tested a bit more and came to the same result i.e the tesseract error. 

This caused me a BSOD on my Win10 because I had Photoshop opened with 70% of ram usage, plus my Vivaldi browser and various tabs opened with about 80% ram usage, I had about 1 gigabyte ram left and when I OCR'ed the .mks file and the error came, a minute later I had a BSOD.

This means there is a memory leak which over buffers the ram and then the BSOD will happen...

**Comment by niksedk** [comment] 2020-01-20 20:28
What happens if you run tesseract.exe via the cmd line?

**Comment by niksedk** [comment] 2020-01-20 20:45
I've tested on three different computers (one is a clean pc with just Visual Studio) and all are working fine... could perhaps be something with "Visual C++ Redistributable"?

To which folder / how did you install SE?

**Comment by OmrSi** [comment] 2020-01-20 20:57
It's also working fine here. Win10 x64, 1909 Build 18363.5592
Maybe try using LSTM only?
![image](https://user-images.githubusercontent.com/20923700/72757174-f43f0680-3bd7-11ea-9ce9-3bbbf96ea25c.png)

**Comment by xylographe** [comment] 2020-01-20 21:03
I tried with Tesseract 4.1.0 and 4.1.1 (Original Tesseract only) on Win7. The results are identical.

**Comment by wtester7** [comment] 2020-01-20 21:19
OK Guys, I have pinpointed the error down: xylographe has the right setting!

**The following Tesseract 4.1.1 settings in SE 3.5.13 are working properly without errors!:**
- Original Tesseract only
- Italic
- Music Symbols
- No Fallback to Tesseract 3.02

**If I choose LSTM Only, LSTM + Tesseract or Default, the fatal error will be triggered, only Original Tesseract only is working!!**

---------------------------------------------------------------------------------------

**All Tesseract 4.1.0 OCR modes in SE 3.5.11 are working without any errors!!!**
- Default, LSTM Only, LSTM + Tesseract or Original Tesseract only
- Italic
- Music Symbols
- No Fallback to Tesseract 3.02

**Comment by wtester7** [comment] 2020-01-20 21:31
As you read above, vivadavid also has the same problem! 

@vivadavid can you please test with these settings:
- Original Tesseract only
- Italic
- Music Symbols
- No Fallback to Tesseract 3.02

and see if it's also the only mode that is working properly for you?

**Comment by vivadavid** [comment] 2020-01-20 22:03
Hi, using the settings suggested by @wtester7, things worked.

None of the other three modes worked.

I'm also using the portable version. As for Visual C++, I have the x86 and x64 versions of C++ 2013 and C++ 2015-2019.

**Comment by xylographe** [comment] 2020-01-20 22:25
I have now tested "LSTM Only" and "LSTM + Tesseravt" too. I also tried disabling "Italic" and/or "Music symbol". All modes/combinations generate acceptable results, though it would appear (first impression only) that the best result (the least errors) is generated by "Tesseract only".

**Comment by xylographe** [comment] 2020-01-21 03:52
Just a wild guess. Is there any chance that the problems are caused by a missing `osd.traineddata`?

**Comment by wtester7** [comment] 2020-01-21 09:19
Nope! I'm am very sure somethings have changed in Tesseract 4.1.0 to 4.1.1 that is causing the problems. 

**Why is that only "Original Tesseract only" mode is working properly and the other 3 modes are defect? How do the other 3 modes differ? Why is that in Tesseract 4.1.0 all modes in SE 3.5.11 are working without any errors!?**

**Comment by wtester7** [comment] 2020-01-21 09:37
I have an idea how to further pinpoint the problem. How about @niksedk or an other helping dev can compile Tesseract 4.1.1 for SE 3.5.11 so I can test it and see if it's working properly. We can then exclude or see if the changes that have been made since 3.5.11 to 3.5.13 are causing the problem. If the commits are not the fault then it's Tesseract 4.1.1

**Comment by xylographe** [comment] 2020-01-21 09:50
In the folder where you have extracted SE 3.5.11 you open the `Tesseract410` folder. You rename the `tesseract.exe` file in that folder to `tesseract.exe.410`. Copy or link the new Tesseract 4.1.1 executable to that folder, and start SE.

**Comment by wtester7** [comment] 2020-01-21 10:00
Ok, so it really is the new Tesseract 4.1.1. I have just tested it and in SE 3.5.11 it is the same problem! Only the mode "Original Tesseract Only" is working fine, all other modes ( Default, LSTM Only, LSTM + Tesseract )  are crashing!

**Comment by xylographe** [comment] 2020-01-21 10:29
For now, anyone experiencing problems with Tesseract 4.1.1, can download [`Tesseract410.tar.gz`](https://github.com/SubtitleEdit/support-files), and replace the new `tesseract.exe` in SE-3.5.13 (the containing folder is named `Tesseract411`)  with the old `tessseract.exe`.

**Comment by vivadavid** [comment] 2020-01-21 14:16
Thank you, @xylographe. I've just tried your suggestion and it works!

First, I deleted the <tessdata> folder too, but SE didn't prompt me to download the trained data files, as the programme thought that they had already been downloaded; as a result, I couldn't do the OCR.

My next step was to restore the <tessdata> folder with the files downloaded with Tesseract 4.1.1. It worked!

SE still shows Tesseract 4.1.1, while the file tesseract.exe corresponds to Tesseract 4.1.0 and the trained data corresponds to 4.1.1. Is that correct?

**Comment by niksedk** [comment] 2020-01-21 14:21
@wtester7 / @vivadavid: what happens if you run tesseract in the command prompt?
See https://github.com/tesseract-ocr/tesseract/wiki/Command-Line-Usage

**Comment by wtester7** [comment] 2020-01-21 14:42
cmd: tesseract 00003.mks test.srt --oem 1 -l eng

**Tesseract Open Source OCR Engine v4.1.1 with Leptonica
Error during processing.**

---------------------------------------------------------------------------------------

cmd: tesseract 00003.mks test.srt --oem 0 -l eng

**Tesseract Open Source OCR Engine v4.1.1 with Leptonica
Error during processing.**

**Comment by niksedk** [comment] 2020-01-21 14:56
@wtester7: Could you try a .png image with all engine modes in cmd line (via the "oem" parameter) ?


      0    Legacy engine only.
      1    Neural nets LSTM engine only.
      2    Legacy + LSTM engines.
      3    Default, based on what is available.

**Comment by vivadavid** [comment] 2020-01-21 15:00
I had never used the command line with Tesseract, but I gave it a try with a PNG file containing English text.

Using oem 1, the output file was empty:
tesseract image.png output --oem 1 -l eng

Using oem 0, it worked:
tesseract image.png output --oem 0 -l eng

Then I tried with the MKS file.

Using either oem 0 or eom 1, I got the same error message ("Error during processing"):
tesseract 00003.mks output --oem 1 -l eng
tesseract 00003.mks output --oem 0 -l eng

**Comment by vivadavid** [comment] 2020-01-21 15:03
Sorry, I've just seen your message, @niksedk 

With the PNG file, I tried --oem 2 and --oem 3: in both cases, I got no error message and the file was empty.

tesseract image.png output --oem 2 -l eng
tesseract image.png output --oem 3 -l eng

**Comment by wtester7** [comment] 2020-01-21 15:06
tesseract test.png test.srt --oem 0 -l eng = works, written ocr file!
tesseract test.png test.srt --oem 1 -l eng = empty text file
tesseract test.png test.srt --oem 2 -l eng = empty text file
tesseract test.png test.srt --oem 3 -l eng = empty text file

**Comment by vivadavid** [comment] 2020-01-21 15:08
Same results as @wtester7.

**Comment by wtester7** [comment] 2020-01-21 15:28
Some idea to consider, I have a pretty old 6-Core CPU I7-970 that is 10 years old now but still rocking ;-) , maybe there are some new added features/changes ( since Tesseract 4.1.0 ) to the latest Tesseract 4.1.1 that is not compatible with old CPU's?

**Comment by vivadavid** [comment] 2020-01-21 15:38
I found this information on https://github.com/UB-Mannheim/tesseract/wiki:

"We don't provide an installer for Tesseract 4.1.0 because we think that the latest version 5.0.0-alpha is better for most Windows users in many aspects (functionality, speed, stability). Version 4.1 is only needed for people who develop software based on the Tesseract API and who need 100 % API compatibility with version 4.0."

There's something going on with Tesseract 4.1.(x) if they don't recommend using it. The funny thing is that version 4.1.0 didn't cause any trouble, as opposed to 4.1.1

**Comment by vivadavid** [comment] 2020-01-21 15:40
Like @wtester7, my CPU is also quite old: a first generation Intel Core i7.

**Comment by vivadavid** [comment] 2020-03-08 21:39
Hi!

I've tested the issue on 3.5.14 and it's still there. Judging by the changelog, this was expected, but I wanted to try anyway.

Will it be fixed in a future release of Subtitle Edit or do we need to wait for the next version of Tesseract? In the meantime, it might make sense to go back to Tesseract 4.1.0, which didn't show this problem.

**Comment by niksedk** [comment] 2020-03-09 16:10
I think they added some cpu optimizations without checking for support in 4.1.1 - perhaps AVX (it also does run much faster than 4.1.0).

So you can use 3.02 or do the hack of copying the 4.1.0 files to the 4.1.1 folder in SE...

Compiling tesseract is *extremely* difficult.

**Comment by vivadavid** [comment] 2020-03-09 17:45
Thank you, @niksedk . I think they have been working on Tesseract 5 for quite some time now, which will hopefully make things easier.

**Comment by niksedk** [comment] 2020-03-09 17:46
Does the Tesseract 5 alpha work for you?
( used the one from here: https://github.com/UB-Mannheim/tesseract/wiki )
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.14/SubtitleEditBeta.zip

**Comment by vivadavid** [comment] 2020-03-09 18:25
I got an error message.

![2020-03-09 - 19 24 13 - ](https://user-images.githubusercontent.com/9334287/76245200-bfe0e180-623b-11ea-8bf8-553ad2e8be5d.png)

**Comment by niksedk** [comment] 2020-03-13 07:10
@vivadavid / @wtester7: Can you run "tesseract.exe" via command line from this package: https://digi.bib.uni-mannheim.de/tesseract/tesseract-ocr-w32-setup-v5.0.0-alpha.20200223.exe
( for more info see https://github.com/UB-Mannheim/tesseract/wiki )

**Comment by vivadavid** [comment] 2020-03-14 11:07
Hi, @niksedk 

I've tried with every value for --oem and I keep getting an error message.

![2020-03-14 - 12 06 32 - Tesseract 5 (error message)](https://user-images.githubusercontent.com/9334287/76680812-63d7dd80-65ec-11ea-91d1-b197fe7f4359.png)

**Comment by niksedk** [comment] 2020-03-14 11:13
@vivadavid: Was that via tesseract command line and the Mannheim version?
Like `tesseract a.png out -l eng` ?

My guess is that some CPU optmization is enabled, that your cpu does not have...

**Comment by vivadavid** [comment] 2020-03-14 11:33
@niksedk , I installed the programme from the link you gave me and typed commands like this:

tesseract image.png output --oem 0 -l eng

You may be right about the CPU optimization, because my laptop is very old: 1st generation Intel Core.

**Comment by niksedk** [comment] 2020-03-14 18:03
@vivadavid: thx for testing :)

**Comment by vivadavid** [comment] 2020-03-14 18:05
You are welcome :-) , @niksedk 

Thank you for making such a great programme!

**Comment by niksedk** [comment] 2020-03-14 18:09
You're welcome too :)

If you really want this fixed, try creating an issue here: https://github.com/UB-Mannheim/tesseract/issues

**Comment by vivadavid** [comment] 2020-03-15 09:49
Good idea, @niksedk 

I've just done it: https://github.com/UB-Mannheim/tesseract/issues/31

**Comment by niksedk** [comment] 2020-03-15 09:58
@vivadavid: could you attach a screenshot from http://download.cpuid.com/cpu-z/cpu-z_1.91-en.zip ?

Should be like: 
![image](https://user-images.githubusercontent.com/1261331/76699236-dcea3a00-66ab-11ea-97b4-73396b32a18d.png)

My CPU has AVX

**Comment by niksedk** [comment] 2020-03-15 10:02
@wtester7: How does your cpu look like?

**Comment by vivadavid** [comment] 2020-03-15 14:21
There you go, @niksedk . Thank you for taking the interest.

![2020-03-15 - 15 19 47 - CPU-Z](https://user-images.githubusercontent.com/9334287/76703236-880cea80-66d0-11ea-9940-24c4de88e583.png)

**Comment by stweil** [comment] 2020-03-18 21:13
Tesseract from UB Mannheim should work on any Intel or AMD x86 compatible CPU. Anything else would be a bug.

**Comment by stweil** [comment] 2020-03-18 21:15
@vivadavid, did you keep the files from the installation together, or did you move `tesseract.exe` to a different directory?

**Comment by vivadavid** [comment] 2020-03-19 09:37
@stweil , I didn't move anything.

**Comment by wtester7** [comment] 2020-03-19 11:22
![CPU-Z](https://user-images.githubusercontent.com/36233786/77062507-489a1300-69dc-11ea-853a-9710e214230c.jpg)

**Comment by wtester7** [comment] 2020-03-19 11:25
@stweil my path is: E:\Program Files\PortableProgs\Video\Subtitle Edit\Tesseract411\tesseract.exe

**Comment by wtester7** [comment] 2020-03-19 11:54
@stweil I have also tried the new OCR 5 Alpha from: 
https://digi.bib.uni-mannheim.de/tesseract/tesseract-ocr-w32-setup-v5.0.0-alpha.20200223.exe 
I have the same problem like @vivadavid 

![Tesseract_5_Alpha_Error](https://user-images.githubusercontent.com/36233786/77064937-ad576c80-69e0-11ea-9e2e-a174df1512fa.jpg)

**Comment by niksedk** [comment] 2020-03-29 06:26
@wtester7 / @vivadavid : Could you try this new version and see if you still get the crash?
https://digi.bib.uni-mannheim.de/tesseract/tesseract-ocr-w32-setup-v5.0.0-alpha.20200328.exe

**Comment by vivadavid** [comment] 2020-03-29 08:29
Hi, @niksedk 

I get a different kind of error:

Error: Tesseract (legacy) engine requested, but components are not present in C:\Program Files (x86)\Tesseract-OCR/tessdata/eng.traineddata!!

The file is certainly there, so the only problem I can think of is that Tesseract, in this alpha, can't access the subfolder because it's using '/' instead of '\'.

Is there a parameter I can use to tell Tesseract where the trained data is?

**Comment by niksedk** [comment] 2020-03-29 08:43
Try this traineddata file: https://github.com/tesseract-ocr/tessdata/raw/master/eng.traineddata
Contains both legacy and new LSTM. Any better?

**Comment by vivadavid** [comment] 2020-03-29 13:47
Thank you, @niksedk 

Now everything works. All 4 modes running directly Tesseract.exe and also running your beta of SE. I'm very happy! Thanks again!

**Comment by niksedk** [comment] 2020-03-29 13:58
Thank @stweil :)

**Comment by wtester7** [comment] 2020-03-29 13:59
@niksedk and @stweil , yes the new version is working well! Thank you for the fix!!

**Closed by niksedk** 2020-03-29 13:58 UTC

**Comment by wtester7** [comment] 2020-03-29 14:06
Btw, Tesseract 5.00 2020-03-28 Alpha is also much faster than 4.1.1! Thank you again!!

**Comment by vivadavid** [comment] 2020-03-29 14:21
Sorry, I forgot to thank you, @stweil

**Comment by stweil** [comment] 2020-03-29 15:27
You are welcome. Thanks for reporting severe problems like this one.
Best regards from @UB-Mannheim.

**Comment by OmrSi** [comment] 2020-03-29 18:54
Wow. It really is very fast.
