### ISSUE TITLE
blurring of the text in the program when mastabbing at 125%

### ISSUE THREAD

**Issue by AdventurerRussia** [SubtitleEdit/subtitleedit#6596] opened 2023-01-15 11:57 UTC
I have a laptop, so at 100% the elements are very small in it, I had to set 125%.
Many programs will be selected as needed without blurring, but your program has blurred text at 125% of the screen.
125
![Снимок экрана (3)](https://user-images.githubusercontent.com/14019010/212539191-c6e7f98e-51a6-45fd-a041-0a624914061b.png)
100
![Снимок экрана (4)](https://user-images.githubusercontent.com/14019010/212539192-1132c23f-c672-4d43-8e58-8b986c47f59b.png)

HP 15,6" 15-ef2000 (2K3D8AV)

Выпуск	Windows 11 Pro
Версия	22H2
Дата установки	‎22.‎10.‎2022
Сборка ОС	22621.1105
Взаимодействие	Windows Feature Experience Pack 1000.22638.1000.0

**Comment by niksedk** [comment] 2023-01-15 13:07
Dupe of https://github.com/SubtitleEdit/subtitleedit/issues/2434

**Closed by niksedk** 2023-01-15 13:07 UTC
