### ISSUE TITLE
Feature Request:  please add support to convert  video to  .srt  via OCR

### ISSUE THREAD

**Issue by solidmaple** [SubtitleEdit/subtitleedit#4063] opened 2020-03-29 01:32 UTC
Feature Request:  please add support to convert  video to  .srt  via OCR

currently  subtitleedit supports  OCR from   .idx/.vob and .sup but not from video file itself

can subtitleedit  able to use OCR from a video file?

such as this sample example file

https://x0.at/dwp.mp4

**Comment by tonsofpcs** [comment] 2020-03-29 01:36
It seems that converting such a video file to an image sequence and OCRing the image sequence works at present except that the resultant subtitles all start at 0 and have the same duration (except the last one) and there doesn't appear to be an obvious way to simply set them all to a single frame duration and 'bump' the next ones down.  I agree that being able to OCR a video (or, ideally also, a window on a video) into subtitles would be quite useful.

**Comment by uckthis** [comment] 2020-03-29 07:32
Use VideoSubFinder

**Comment by OmrSi** [comment] 2020-09-10 17:49
@niksedk Duplicate of https://github.com/SubtitleEdit/subtitleedit/issues/1328?

**Closed** 2020-11-27 15:57 UTC
