### ISSUE TITLE
The right in cue cannot be snapped to the right side of a green zone while the left out cue is unaffected at the same time.

### ISSUE THREAD

**Issue by Lyubomir71** [SubtitleEdit/subtitleedit#7736] opened 2023-12-14 16:21 UTC
The steps until the error occurs:
1) Beautify time codes
2) Extract  time codes
3) Generate / import shot changes...
_The profile is selected - Netflix_
4) OK -> The error appears 

I am adding a photo of the error for details
![SubtitleEditErrorBTC](https://github.com/SubtitleEdit/subtitleedit/assets/865032/2c1a27ca-fe57-4c1b-9323-2811960319e4)

**Comment by niksedk** [comment] 2023-12-14 17:06
Thanks for the info - could you possibly attach the subtitle file? And possibly the audio file too?

**Comment by Lyubomir71** [comment] 2023-12-14 20:17
Subtitles (in Bulgarian):
[Poldark.2015_S1.E1_1080p_AAC_x265.srt.zip](https://github.com/SubtitleEdit/subtitleedit/files/13677844/Poldark.2015_S1.E1_1080p_AAC_x265.srt.zip)

The audio file - you should have a link to Google Drive in your mail.

Best Regards

**Comment by niksedk** [comment] 2023-12-15 19:17
Thx for the file... could you email a link to the actual video file too (sorry, the audio is not enough).

**Comment by Lyubomir71** [comment] 2023-12-15 22:04
Ready

**Comment by Flitskikker** [comment] 2023-12-16 22:35
@Lyubomir71 @niksedk  

Could you send/forward me the files so I can debug this one on my end?
I think I'll also need the shot changes (Video -> Remove/export shot changes -> Export...).

**Comment by Lyubomir71** [comment] 2023-12-17 10:31
> @Lyubomir71 @niksedk
> 
> Could you send/forward me the files so I can debug this one on my end? I think I'll also need the shot changes (Video -> Remove/export shot changes -> Export...).

Could you give me an email so I can give you access?

**Comment by Flitskikker** [comment] 2023-12-17 12:25
> Could you give me an email so I can give you access?

Sure, you could use flitskikker AT gmail dot com. Thank you.

**Comment by Lyubomir71** [comment] 2023-12-17 15:27
Ready

**Comment by Flitskikker** [comment] 2023-12-17 18:27
@Lyubomir71 

Thank you for the files. I was able to reproduce it on my end, so I will work on a fix.

**Comment by Flitskikker** [comment] 2023-12-17 22:20
The error should be fixed with PR #7754.

The cause was this overlapping subtitle:

![image](https://github.com/SubtitleEdit/subtitleedit/assets/3516155/3e0ee1f2-6ffb-4ee1-8634-a2095a29d8f2)

The in-cue of subtitle 2 (I removed the rest) is in the green zone of the shot change (according to NF rules).
Normally, the out-cue of subtitle 1 is to the left of that, but because it is overlapping, it is 30 seconds to the right, nowhere near a shot change.
That situation wasn't implemented, so it threw an error.

The new PR handles this edge case, and also adds support for overlapping subtitles, so you can have simultaneous subtitles for on-screen texts, as in this example.

**Comment by Lyubomir71** [comment] 2023-12-18 01:22
Perfect! 

Best Regards
Lyubomir Kolev

**Closed** 2023-12-18 08:17 UTC

**Comment by niksedk** [comment] 2023-12-18 18:08
Beta updated to include @Flitskikker fixes: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.2/SubtitleEditBeta.zip
