### ISSUE TITLE
Invalid data was found

### ISSUE THREAD

**Issue by MehdiZouaoui** [SubtitleEdit/subtitleedit#4217] opened 2020-06-04 20:10 UTC
I was trying to download the dictionary for Arabic and I got this error message. I tried with Turkish language and and I got the same message. When I tried with the default first language that shows up in the dropdown menu (Afrikanns) it downloaded it without any problem

Strack trace: 
Location: Nikse.SubtitleEdit.Core.ZipExtractor.Open(Stream stream)
Location: Nikse.SubtitleEdit.Forms.GetDictionaries.wc_DownloadDataCompleted(Object sender, DownloadDataCompletedEventsArgs e)
Location: Net.WebClient.OnDownloadDataCompleted(DownloadDataCompletedEventsArgs e)

**Comment by xylographe** [comment] 2020-06-05 00:16
Duplicate of #4203.

**Closed by xylographe** 2020-06-05 00:16 UTC
Labels: duplicate
