### ISSUE TITLE
Google Translate --- Every Other Line Is Skipped

### ISSUE THREAD

**Issue by UnitedDugout27** [SubtitleEdit/subtitleedit#4680] opened 2021-01-06 14:25 UTC
![image](https://user-images.githubusercontent.com/77062086/103779062-3340b480-5001-11eb-9d05-266c6607e62b.png)

this happened a couple months back. I'm on the latest version as of jan 2021 v3 5 18
how can i fix this?

**Comment by OmrSi** [comment] 2021-01-06 16:33
Can you test the beta version? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.18/SubtitleEditBeta.zip

**Comment by UnitedDugout27** [comment] 2021-01-06 18:58
that's the version i am currently on. same issue.

**Comment by OmrSi** [comment] 2021-01-06 19:10
Are you sure you have the beta version? Or is it the official version?

**Comment by UnitedDugout27** [comment] 2021-01-07 01:25
I downloaded the zip file you linked to, and i still have the same issue.

**Comment by lambdacore12** [comment] 2021-01-07 10:20
@UnitedDugout27 could this be a duplicate of #4534?

**Comment by UnitedDugout27** [comment] 2021-01-07 14:17
it looks like it. there is an option at the bottom left corner that allows you to set the mode to merge and not merge.
selecting not merge bring the translation option back to the way it used to be.

**Comment by OmrSi** [comment] 2021-01-07 14:23
That's why I wanted you to test the beta.
That option was added very recently.

**Closed** 2021-01-07 14:32 UTC
Labels: duplicate
