### ISSUE TITLE
Feature request:  Extracting Burned-in subtitles

### ISSUE THREAD

**Issue by fraternl** [SubtitleEdit/subtitleedit#8094] opened 2024-03-29 10:01 UTC
I once had 2 versions of a movie.
1 with burned-in subtitles of my language and one without any burned-in subtitles.
I went through some lengthy complicated procedure to extract those burned-in subtitles and got OCR's ones.

If SE could do this, like it does with VOB- and SUP-files with Tesseract, this would be great.

I still have the need to do this sometime, but I don't want to do that procedure anymore which took a lot of time.
In the end I only did it once.
It did give me a nice subtitle, though.

**Comment by niksedk** [comment] 2024-03-29 12:39
Duplicate of https://github.com/SubtitleEdit/subtitleedit/issues/340 and probably https://github.com/SubtitleEdit/subtitleedit/issues/1328 too

**Closed by niksedk** 2024-03-29 12:39 UTC
