### ISSUE TITLE
[Feature request] Deep OCR - Extract Subtitle from Hardcoded Videos

### ISSUE THREAD

**Issue by Daredevil74** [SubtitleEdit/subtitleedit#8224] opened 2024-04-18 21:56 UTC
Hello
pls add this feature to SE by [this project](https://github.com/PaddlePaddle/PaddleOCR) ([+](https://github.com/devmaxxing/videocr-PaddleOCR)) if you can

`Awesome multilingual OCR toolkits based on PaddlePaddle (practical ultra lightweight OCR system, support 80+ languages recognition, provide data annotation and synthesis tools, support training and deployment among server, mobile, embedded and IoT devices)`

thanks for everythings

**Comment by niksedk** [comment] 2024-04-19 05:57
Dupe of https://github.com/SubtitleEdit/subtitleedit/issues/340

**Closed by niksedk** 2024-04-19 05:57 UTC
