### ISSUE TITLE
cant download the models

### ISSUE THREAD

**Issue by kd0frg** [SubtitleEdit/subtitleedit#7289] opened 2023-08-26 18:30 UTC
i try to download the models, it doesn't list large v2, and only a few kb downloads, some pt file.. it doesn't download anything.. it just closes.. and leaves some blank file name

tiny, small, medium.. none of them download

I've tried putting the largev2 from your download page in the models folder.. yet it is still not selectable in the drop-down menu within subtitle edit?

**Comment by niksedk** [comment] 2023-08-27 08:51
Model download links were changed... should be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip
(Final will be out soon)

Dupe of: #7230 + #7158 + #7179 + #7060

**Closed** 2023-09-03 10:06 UTC
