### ISSUE TITLE
IDX/SUB (VOBSUB) subtitle position

### ISSUE THREAD

**Issue by webmogul1** [SubtitleEdit/subtitleedit#6636] opened 2023-02-01 03:40 UTC
Is it possible to get the subtitle position from the idx/sub and apply to Advanced Substation Alpha?
It is particularly useful when you have other text behind the subtitle. Like that:
![image](https://user-images.githubusercontent.com/5225701/215939637-15ad0a17-c693-48dd-bfb2-edbcb6cb1136.png)

Subextractor does that but its ocr is too basic.

**Comment by niksedk** [comment] 2023-03-08 19:57
Dupe of #3801

**Closed by niksedk** 2023-03-08 19:57 UTC
