### ISSUE TITLE
An error with Microsoft Translate

### ISSUE THREAD

**Issue by MehdiZouaoui** [SubtitleEdit/subtitleedit#4296] opened 2020-08-06 15:30 UTC
I've added Microsoft Translator API to the program but when I click on "translate" an error message shows up ( it showed up in Turkish and below is my translation:

_An application error occured in Subtitle Edit 3.5.16.0_

Error message: the identified value contains an invalid CRFL characters.

Stack Trace
Location: System.net.WebheaderCollection.CheckbadChars(string name, Boolean is HeaderValue)
Location: System.net.WebHeaderColleciton.Add (string name, String value)
Location: Nikse.SubtitleEdit.Core.Translate.MicrosoftTranslator.Translate (String sourceLanguage, String targetLanguage, List1 paragraphs, StringBuilder log)
Location: Nikse.SubtitleEdit.Forms.GoogleTranslate.Translate (String source, String target, ITranslator, Int32 maxTextSize, In32 maximumRequestArrayLength)
Location: Nikse.SubtitleEdit.Forms.GoogleTranslate.ButtonTranslate_Click(Object sender, EventArgs e)

I've uploaded a screenshot of the error message and uploaded it to Google Drive [https://drive.google.com/file/d/1EUw0AnRkr0q73AM-DP4SFnjY2UbF3NJb/view?usp=sharing ](url)

**Comment by niksedk** [comment] 2020-08-06 16:23
Closed as duplicate of #4297

**Closed** 2020-08-06 16:24 UTC
