### ISSUE TITLE
Non-responsive after changing input language

### ISSUE THREAD

**Issue by spellr** [SubtitleEdit/subtitleedit#4219] opened 2020-06-05 11:23 UTC
I'm on Windows 10, I have US keyboard + Hebrew keyboard.
To reproduce:

1. Insert new subtitle at video pos
2. Start typing in English
3. Switch to hebrew
4. Can't type anymore, neither in English nor Hebrew
5. Only way to type again is to exit the program an re-open it

**Comment by darnn** [comment] 2020-06-05 11:41
I have the same setup and I can't reproduce this at all.

**Comment by OmrSi** [comment] 2020-06-05 13:22
Are you changing it using Win+space or Alt+shift?
If it's Win+space, there was a bug concerning the windows-key but it's fixed in the latest beta.

**Comment by spellr** [comment] 2020-06-05 14:22
win+space :)

**Comment by OmrSi** [comment] 2020-06-05 14:24
And have you tried the lastest beta?

**Comment by spellr** [comment] 2020-06-05 15:07
> And have you tried the lastest beta?

How can I try it? It's not in the releases page

**Comment by xylographe** [comment] 2020-06-05 15:11
It is in the [latest release](https://github.com/SubtitleEdit/subtitleedit/releases/latest).
Direct link is [`SubtitleEditBeta.zip`](https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.15/SubtitleEditBeta.zip).

**Comment by spellr** [comment] 2020-06-05 15:22
I've tried the beta.
After hitting win+space, There's a ~2 seconds delay in which I can't type. After that delay I can type normally.
alt+shift works fine.

**Closed** 2020-06-13 07:02 UTC
