### ISSUE TITLE
Audio to text error

### ISSUE THREAD

**Issue by citizendrastique** [SubtitleEdit/subtitleedit#6249] opened 2022-09-13 19:38 UTC
I was traying to generate text from audio. I installed english and spanish. This error happend. 
![error transcript](https://user-images.githubusercontent.com/68475587/189993755-d99a201f-3aa1-4627-84e2-d7e8bf179d4d.JPG)

**Comment by niksedk** [comment] 2022-09-14 05:51
Are you using VLC as video player in SE ?

**Comment by niksedk** [comment] 2022-09-14 16:16
Also probably a duplicate of #6193

**Closed** 2022-09-14 16:16 UTC
