### ISSUE TITLE
[Feature Request] Resample Resolution option

### ISSUE THREAD

**Issue by JySzE** [SubtitleEdit/subtitleedit#5229] opened 2021-07-27 22:11 UTC
Add resample resolution like aegisub has which can change the pos and blur values

example: 

Original 704,528 res:
Dialogue: 0,0:04:18.44,0:04:23.41,Title,,0,0,0,,{\blur0.6\pos(363.167,227.751)}Enter!

Resampled to 704,480:
Dialogue: 0,0:04:18.44,0:04:23.41,Title,,0,0,0,,{\blur0.545\pos(363.167,207.046)}Enter!

Also making this batch supported would be amazing too.

**Comment by niksedk** [comment] 2021-07-29 11:51
How does latest beta work for you: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.1/SubtitleEditBeta.zip ?

![image](https://user-images.githubusercontent.com/1261331/127487053-45585e8c-7715-404a-8c6b-a4b6137a90ff.png)


I will close this... looks like a duplicate of https://github.com/SubtitleEdit/subtitleedit/issues/5202

**Closed by niksedk** 2021-07-29 11:51 UTC
