### ISSUE TITLE
Size of UI elements

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#7109] opened 2023-07-16 18:43 UTC
I've tried the latest beta, and there, thankfully, the duration becomes visible again (before the width wasn't enough to display anything except the things after the decimal point).
However, it still seems like things don't look exactly as they should. Compare your image:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/19672444/7056982d-c99b-42fd-8d5b-756de446589d)
With what it looks like on my end:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/19672444/689d7f3a-50b2-4e9c-81ac-7ffee4d48c6f)
Note also "video position" and the way "select current subtitle while playing" gets a few pixels into the video player space.
This isn't a huge concern, but I'd still love it to... not be this way. I assume it might have something to do with my Windows settings, so I'll gladly tell you anything beyond the obvious things, which are that my resolution is 1920x1080, the "size of text, apps and other items" is 100%, and "let Windows try to fix apps so they're not blurry" is off, but turning it on has no effect on Subtitle Edit.

**Comment by niksedk** [comment] 2023-07-17 15:50
OK, setting a larger text size I get something similar:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/a704f1f3-d1a8-448c-b1cd-4f9a5895c197)

It might be possible to lower the font size... or try to resize controls - which sounds best?

**Comment by darnn** [comment] 2023-07-17 17:12
Huh. It's weird that our settings are the same and yet my font size is indeed larger for some reason.
As for which sounds best, maybe just making the font size something the user can change? That way if there are any other unexplained situations like mine, people could try and find something that fits their particular case?

**Comment by niksedk** [comment] 2023-07-18 05:33
I'm not sure how much I can do... 
How is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip

**Comment by darnn** [comment] 2023-07-18 07:34
This is what it looks like now...
![image](https://github.com/SubtitleEdit/subtitleedit/assets/19672444/9a908ecd-59ac-4d22-97ca-b4ab8a8ef29f)

Frankly, if anything beyond this is too hard, I can definitely live with it.

**Comment by darnn** [comment] 2023-07-20 20:34
The crash seems to be fixed. Ctrl+C continues to not work, however. I rebooted just to be on the safe side, and right now it works in the version from May, like it did before, but not in the current beta. Should I open a separate issue for this?

**Comment by darnn** [comment] 2023-07-21 15:54
Another thing that seems to be related to this is that in the Start Time box (next to Duration), you can't copy, paste etc. with the keyboard either, and also, at least in frame mode, if you set a specific time there and then click or tab away, the time will move one frame back. So if you've set it to 00:00:00:00 it will move to -00:00:00:01. This seems to not happen every time, but it does happen if you create a new line using insert before/insert after, and then change its start time.

**Comment by niksedk** [comment] 2023-07-21 17:34
Thx :)

Tried to fix it here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip 
How does it work?

**Comment by darnn** [comment] 2023-07-21 18:44
Seems to work well now! I'd like to try it for a few more days to make sure, but I can definitely do all the stuff I couldn't before. 
One odd thing, though:
Create a new file. Insert a new line. From the text box, use shift+tab to navigate to Start Time. It should be 00:00:01:00. Navigate to the 1 using the keyboard's arrow keys and change it to 0, then press enter. Use the keyboard shortcut for "insert new line after". Use the keyboard shortcut to navigate back to the first line in list view (alt+up in my case). Use shift+tab to get to Start Time again. Now try to type a number. The Start Time box won't behave like it's supposed to. I'm sure that's a lot to follow, so here it is in gif form:
![se 7-21-2023 9-41-36 PM](https://github.com/SubtitleEdit/subtitleedit/assets/19672444/7dc0e8e8-1f13-45e2-9d9b-b4b57ef2a3c4)

**Comment by niksedk** [comment] 2023-07-22 07:13
Thx :)
OK, hopefully better now: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip ?

**Comment by darnn** [comment] 2023-07-22 11:16
I'm afraid it's still happening, same steps to reproduce it... Here's my settings file, in case that might affect it somehow:
[Settings.xml.txt](https://github.com/SubtitleEdit/subtitleedit/files/12136249/Settings.xml.txt)

**Comment by niksedk** [comment] 2023-07-22 15:54
Hm, I cannot re-create the issue with this beta:
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip

**Comment by darnn** [comment] 2023-07-22 16:35
Still happening here, alas...
I tried with a clean settings file, and that didn't change anything, but I did find an even quicker way of reproducing it:
Open SE. Use the "insert after" keyboard shortcut (so alt+ins with a fresh settings file). Press shift+tab four times. Move the cursor to before the 1 and type 0, so it overwrites the one. Press enter. Press end (optional, but this is what I did here). Now try to type a number, and the bug occurs:
![se GIF 7-22-2023 7-31-20 PM](https://github.com/SubtitleEdit/subtitleedit/assets/19672444/a39cdb69-1481-43c1-a791-2693defd1391)

**Comment by niksedk** [comment] 2023-07-23 12:19
thx - yet another test version: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip

**Comment by darnn** [comment] 2023-07-23 12:31
Seems to be working well now! You can close this if you want, I'll switch to this build fully and if anything else comes up I'll let you know.

**Comment by darnn** [comment] 2023-07-23 12:51
Oh, huh. Yeah, happens here too. Didn't think to try typing in the Duration box.

**Comment by niksedk** [comment] 2023-07-23 13:54
Duration box updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip

**Comment by Flitskikker** [comment] 2023-07-23 14:09
@niksedk 
Great, thanks for the quick fix!

One additional thing I discovered (sorry...)

![image](https://github.com/SubtitleEdit/subtitleedit/assets/3516155/f2d89015-0669-4e11-ba3b-30e46faf57a1)

When I do backspace here and then type "2" to change it into "2,500", it leaves the 0 and adds the 2 in front:

![image](https://github.com/SubtitleEdit/subtitleedit/assets/3516155/e1cf17df-1f58-4812-b370-d069ea906cdc)

---

It _does_ work for the milliseconds after the comma.

![image](https://github.com/SubtitleEdit/subtitleedit/assets/3516155/63c6b8b3-b66d-44eb-89d8-1212a82294fd) > backspace > type "75" = ![image](https://github.com/SubtitleEdit/subtitleedit/assets/3516155/f202e2c5-1ca7-4c54-8c49-c22421ada817) 👍

**Comment by niksedk** [comment] 2023-07-23 14:41
It's hopefully a little better now: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip

Alternatively, a masked text box might be used...

**Comment by Flitskikker** [comment] 2023-07-23 15:29
@niksedk 
Thank you, the interaction works great now!

---

There is, however, something else I noticed when using the latest Beta version:
I noticed that beautifying time codes suddenly takes much longer, and that undoing and redoing is not working properly anymore.

I did some testing by checking out commits on main, until the issue started appearing.

This is the last commit where beautifying was still fast, and where undo+redo was still working:
https://github.com/SubtitleEdit/subtitleedit/commit/e46f4e4092115f94c73540052029505e4b47cbee

Starting with this commit, beautifying timecodes is suddenly much slower (several seconds instead of ~500 ms on a 42 minute video + 423 subtitles):
https://github.com/SubtitleEdit/subtitleedit/commit/687be44fd941bdc740eceecd19cd0ce423ea8f71
(Undo and redo are still working)

Starting with this commit, undo and redo are behaving strangely:
https://github.com/SubtitleEdit/subtitleedit/commit/cc77023f2d35645fc18e90cf4db6996a9f8f7123

My steps:
1. I run beautify time codes
2. I press Ctrl+Z, but the beautifying action is not undone. Strangely enough, the status bar says "Undo performed: Display time adjusted: #1: 00:00:06,673 -> 00:00:06,673"
3. I press Ctrl+Z again. The beautifying action is now correctly undone. The status bar says "Undo performed: Before beautifying time codes"
4. I press Ctrl+Y, but nothing happens. The status bar also doesn't show anything.

---

I'm not sure what is going on... If I had to guess, maybe the new control is repainting during `Application.DoEvents()` on every `timeCodesBeautifier.ProgressChanged` callback? I tried adding debug prints to some of the new and updated methods in the control, but I didn't get excessive prints while the time codes beautifier was running, so I'm at a loss...

For the undo+redo, the status bar message suggests that it might be updating more frequently than before.

If you want to test this on your end, I think you could try it with any 40+ min. video (with detected shot changes) and any subtitle with 400+ lines. It doesn't have to be a subtitle that matches the video for testing.

**Comment by niksedk** [comment] 2023-07-23 18:21
Is latest beta okay?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip

**Comment by Flitskikker** [comment] 2023-07-23 18:36
> Is latest beta okay? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip

@niksedk 
No change in both issues, unfortunately.

**Comment by niksedk** [comment] 2023-07-23 18:44
Hm, you can try the Debug - Performance profiler - Alt+F2

It seems pretty fast here...

**Comment by Flitskikker** [comment] 2023-07-23 18:50
@niksedk 
I will check. In the meantime, can you reproduce the undo+redo issue there?

You could try:

1. Change the duration of a subtitle (by extending in waveform or by using the new control)
2. Press Ctrl+Z
3. Try pressing Ctrl+Y. For me it doesn't repeat the action. Also, Edit > Redo stays grayed out.

It does work for start time changes.

**Comment by niksedk** [comment] 2023-07-23 18:53
The performance stuff mostly complains about this:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/e68fd63e-127f-4ef7-ad26-e4de337e388a)

**Comment by niksedk** [comment] 2023-07-23 19:09
I've tried to improve the progress a little... perhaps this can be optimized a little?
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/dd5c3c39-c160-4809-bbd2-e468f71867a8)

**Comment by Flitskikker** [comment] 2023-07-23 19:26
@niksedk 
Hmm... I think it's to be expected that the progress callback is using higher CPU while running the beautifying action, but I agree a background thread would be better.

I checked the Performance profiler on commit e46f4e4092115f94c73540052029505e4b47cbee and on the latest main, and it appears that the control is calling OnPaint a lot in the latest commit (if I understand the profiler correctly):

![image](https://github.com/SubtitleEdit/subtitleedit/assets/3516155/8ef2aaee-6399-4e90-9c7c-4030604cf7fa)
On commit e46f4e4092115f94c73540052029505e4b47cbee, mostly waveform paint calls to update the waveform after beautifying.

![image](https://github.com/SubtitleEdit/subtitleedit/assets/3516155/ec0d166d-44ef-493e-9ad4-1e973a3f00ce)
On main, OnPaint seems to be called a lot during beautifying.

**Comment by Flitskikker** [comment] 2023-07-23 19:28
When I comment out this line on latest master, the slowdown goes away:

![image](https://github.com/SubtitleEdit/subtitleedit/assets/3516155/bbd91645-a8a2-4883-badf-5163425fc9a3)

https://github.com/SubtitleEdit/subtitleedit/blob/0eaa058ba7b226df3a7d7f5c535e2cbd12912427/src/ui/Controls/NikseTimeUpDown.cs#L764

**Comment by Flitskikker** [comment] 2023-07-23 19:46
OK, with the latest-latest main including the new progress calculation, it is also very fast as before. 😁

The UpDown control was probably also being updated during `Application.DoEvents()` then, I think.
If that is the case, maybe there is still something else still going on... Its OnPaint is indeed continuously called:

![image](https://github.com/SubtitleEdit/subtitleedit/assets/3516155/1f44ed61-cb75-45fd-9ee3-e49ba24acc13)

But I'm already happy that changing the progress callback made so much of a difference.

**Comment by niksedk** [comment] 2023-07-24 03:08
Latest main should not paint as much?

**Comment by niksedk** [comment] 2023-07-25 05:16
Hopefully the history is fixed via this commit; https://github.com/SubtitleEdit/subtitleedit/commit/a784236846d17f934f7956543f6d545c488ae875

**Closed by niksedk** 2023-07-25 05:16 UTC
