### ISSUE TITLE
Error downloading the Spanish dictionary

### ISSUE THREAD

**Issue by raulpuro** [SubtitleEdit/subtitleedit#4227] opened 2020-06-07 17:10 UTC
This error is reproduced when trying to download the dictionary for Spain.

<a href="https://ibb.co/1GFMGFZ"><img src="https://i.ibb.co/1GFMGFZ/Imagen1.jpg" alt="Imagen1" border="0"></a>

Greetings and thanks

EDIT: fixed by downloading the beta version:
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.15/SubtitleEditBeta.zip

**Comment by OmrSi** [comment] 2020-06-07 17:38
Yep.
Duplicate of https://github.com/SubtitleEdit/subtitleedit/issues/4203

**Closed** 2020-06-09 12:28 UTC
Labels: duplicate
