### ISSUE TITLE
Splitting two-line subtitles into two separate subtitles.

### ISSUE THREAD

**Issue by vaclavmuller** [SubtitleEdit/subtitleedit#6755] opened 2023-03-16 19:54 UTC
I would like the option to automatically convert all the double-line subtitles into two separate subtitles.

**Comment by LeonCheung** [comment] 2023-03-19 10:48
As long as you don't care about the accuracy of new time codes...

**Comment by LeonCheung** [comment] 2023-03-19 10:52
I think it's duplicate of #4531

**Closed** 2024-04-20 18:15 UTC
Labels: wontfix
