### ISSUE TITLE
Error translate Google + API Key problem

### ISSUE THREAD

**Issue by kotlet1711** [SubtitleEdit/subtitleedit#3663] opened 2019-07-20 14:20 UTC
Hello. Do you know what is causing that when I do a translation using Google Translator in the program Subtitle Edit, I get a row of numbers and letters every time, here's an example:

> 2
00:00:03,964 --> 00:00:06,392
2e1b4477c1b3c12a0683e5c923e09145 - skręcić jakąś sukę?
2e1b4477c1b3c12a0683e5c923e09145 - Obserwuj swoje usta, <i> puto!</i>

3
00:00:06,416 --> 00:00:08,781
2e1b4477c1b3c12a0683e5c923e09145 - Kim ona
jest? - Ona jest byłym narzeczonym Booza.

4
00:00:08,805 --> 00:00:11,162
2e1b4477c1b3c12a0683e5c923e09145 - A ona jest teraz
z tobą. 2e1b4477c1b3c12a0683e5c923e09145 <i> - Sí.</i>

5
00:00:11,163 --> 00:00:13,374
2e1b4477c1b3c12a0683e5c923e09145
Poddajesz to swojej pańskiej szefowej?
> 

How to get rid of it?
The latest version of the program is like what.

Another problem.
After entering the API key from Google in the automatic translation program, I get an error:
System: The remote server returned an error (403). It prohibited.
When I remove the API key from the program, this error does not appear.
How to solve it?

**Comment by xylographe** [comment] 2019-07-21 03:25
To get rid of it you could replace `[0-9a-f]{32}\040` with the empty string.

**Comment by kotlet1711** [comment] 2019-07-22 06:15
**xylographe **, ok, where should I change it?

**Comment by xylographe** [comment] 2019-07-22 09:31
Sorry, I meant removing the ‘clutter’ after the translation, by adding a new "Regular expression" (with the "Find what" field set to `\b[0-9a-f]{32}\b\040?` and the "Replace with" field empty) to **Edit > Multiple replace**.

I'm afraid, I don't know how to _prevent_ the occurrence of these strange hexadecimal sequences.

**Comment by niksedk** [comment] 2019-07-27 14:22
Closed as duplicate of #3632

**Closed by niksedk** 2019-07-27 14:22 UTC
