### ISSUE TITLE
Error when downloading Indonesian dictionary

### ISSUE THREAD

**Issue by kempol181** [SubtitleEdit/subtitleedit#4222] opened 2020-06-06 05:27 UTC
![1](https://user-images.githubusercontent.com/41830084/83936791-16d16500-a7f1-11ea-883e-2d7dfc49383f.PNG)

**Comment by xylographe** [comment] 2020-06-06 08:26
Duplicate of #4203.

**Closed by xylographe** 2020-06-06 08:26 UTC
Labels: duplicate
