### ISSUE TITLE
Cannot open video(mp4) file [Windows Update KB4013429]

### ISSUE THREAD

**Issue by DaveJ32** [SubtitleEdit/subtitleedit#2292] opened 2017-03-15 18:52 UTC
Trying to open a video file cause the software to crash. I tried uninstalling, used older version and so on, but it didn't solve anything.

**Comment by ivandrofly** [comment] 2017-03-15 20:38
Have you tried to open your mp4 file outside subtitle edit? Did it work fine?

**Comment by SirEllert** [comment] 2017-03-16 13:08
+ to thread starter. 

Using Windows 10, trying to drag in several kind of video types(.mov, .ts, .mp4, .mpeg) all causes Subtile Edit to crash. 
All videos i've tested works outside of Subtitle Edit. Checked subtitle for any uncommon signs, lines or so as well.

**Comment by niksedk** [comment] 2017-03-17 04:41
What video player are you using inside SE?
Might have something to do with a windows update...

**Comment by susinz** [comment] 2017-03-17 05:23
Had the same problem... switched from 'Direct Show' to VLC player - now it works!

**Comment by SirEllert** [comment] 2017-03-17 06:26
For some reason I can't select VLC player, as @susinz mentions(but i used to... hmm)

@niksedk i use Media Player Classic(MPC HC), and even if I change from DirectShow to MPC-HC in options, it still crashes.
It's very likely that it has something to do with the windows update, since I had a windows update installed yesterday.

**Comment by explosiveskull** [comment] 2017-03-17 06:54
@SirEllert I think you should install the version that fits your operating system for VLC. That means if you're on an x64 system, you should install the x64 version of VLC to get it working in SE.

**Comment by SirEllert** [comment] 2017-03-17 07:11
@explosiveskull just downloaded and installed 64 bit VLC player.
Correct, now I can choose it in options, but SE still crashes. :-(

**Comment by niksedk** [comment] 2017-03-17 17:49
@SirEllert: How goes with "mpv" video player?
Also, do you know which update that causes the problem?

**Comment by susinz** [comment] 2017-03-18 08:44
One day later... I'm still frustrated! It works with VLC but everything gets very sluggish (especially when working with waveform). Mpv works better but SE still crashes every 20 minutes or so... it goes "bing" and everything freezes... NOT much fun :(

**Comment by SirEllert** [comment] 2017-03-18 10:43
@niksedk i don't have mpv video player codec installed,
but here is a screenshot of the latest windows updates: 

![windowsupdate](https://cloud.githubusercontent.com/assets/14052609/24071356/0b9a0b8a-0bd0-11e7-8da0-05a44035ce81.png)

**Comment by theurbanjedi** [comment] 2017-03-18 19:57
I had the same problem and let me tell you, it went away like a charm when i unistalled two of the latest updates KB3150513 and KB4013429. Of course, windows 10 being windows 10, it installed the update KB4013429 again today so the problem returned so it's safe to say this is the update that's causing the issue.

**Comment by niksedk** [comment] 2017-03-19 08:09
It sounds like it's enough to uninstall "KB4013429".

I have installed this update and everything works fine here, so I don't have a clue about the problem.
You could try to re-install the latest .net framework: https://www.microsoft.com/en-us/download/details.aspx?id=53344 - does that help?
Does the portable version (without installer) work?

**Comment by dbsbug** [comment] 2017-03-19 14:18
Directed here from the blog.  I will try removing KB4013429 as mentioned - and this does seem like this is a temporary fix since Windows 10 will install it again.

I will say that I tried the portable version (with KB4013429 still installed) and experienced the same problem.

**Comment by theurbanjedi** [comment] 2017-03-19 14:41
I had to disable windows update for now by setting my connection as metered cause I really need subtitle edit to work :) i hope that future updates will correct this mistake but for now I'm choosing a functional program over security updates.

**Comment by niksedk** [comment] 2017-03-19 14:44
It seems that this update really crashes programs using DirectShow:

https://www.reddit.com/r/sysadmin/comments/5zw5r3/heads_up_windows_10_kb4013429_makes_applications/

https://www.codecguide.com/  

https://www.xsplit.com/blog/windows-10-update-issues-kb4013429


Hopefully MS will fix this soon...

**Comment by niksedk** [comment] 2017-03-19 14:52
Also, note that KB4013429 is for "quality improvements" (not security updates!) : https://support.microsoft.com/en-us/help/4013429/windows-10-update-kb4013429

So it should be safe to ignore this one update.

**Comment by DaveJ32** [comment] 2017-03-20 04:01
Dang it, I should have uninstall that update when I got the chance. Now I can't go to previous version because it's been 10 days since the I updated mine.

**Comment by SirEllert** [comment] 2017-03-20 06:56
>  It seems that update KB4013429 really crashes programs using DirectShow:
> 
> https://www.reddit.com/r/sysadmin/comments/5zw5r3/heads_up_windows_10_kb4013429_makes_applications/
> 
> https://www.codecguide.com/
> 
> https://www.xsplit.com/blog/windows-10-update-issues-kb4013429
> 
> https://forum.team-mediaportal.com/threads/1-16-pre-rel-crashes-after-w10-update.136308/
> 
> Hopefully MS will fix this soon... 
> 

The only fix that worked for me, was uninstalling the update. 
As I can read on some of these links, a lot of users already reported this issue to microsoft. So hopefully they'll come with a fix soon :-)

**Comment by SuperSluc** [comment] 2017-03-20 12:55
I de-installed the update and yes indeed it works, BUT ......... I've another PC were the update is installed as well and no errors / crashes occur. Both PC's run W10, are both 64 bit, both run the same version of Subtitle Edit 3.5.2.

**Comment by SirEllert** [comment] 2017-03-20 14:16
@SuperSluc i don't know if this is including you, but it was mentioned in one of the links above, that this should only affect users who upgraded from W7 to W10. 

People with pre-installed W10 should not be affected by this. 

@niksedk you're aware of this? ^ 
Curious as you said, it worked on your PC :-)

**Comment by niksedk** [comment] 2017-03-20 15:11
@SirEllert: Thx for the info. No, I was not aware of that... and yes, my win10 installation is a clean install.

**Comment by DarkRvR** [comment] 2017-03-20 16:56
I had same problem that MP4 videos made program crash. I got it working again by uninstalling [Windows Update KB4013429] as mentioned above. Using Windows 10. Also I disabled Windows Updates from Administrative Tools -> Services -> Windows Update (wuauserv) and change "Startup type" to Disabled and  stopped the service. So far been working for me.

**Comment by SuperSluc** [comment] 2017-03-20 19:28
A clean pre-installed W10 is not the case. My problem PC had a W7 to W10 migration indeed, but my other PC had an upgrade as well. This one was upgraded from W8+ to W10

But I just discovered another difference. The trouble machine runs W10 Pro, the Non-problem PC runs W10-Home

**Comment by niksedk** [comment] 2017-03-21 08:49
Fixed in Windows update KB4015438 :)
https://support.microsoft.com/en-us/help/4015438/windows-10-update-kb4015438

Can anyone confirm?

**Comment by SirEllert** [comment] 2017-03-21 11:21
I can confirm that the above update fixes the issue :-)

**Comment by SuperSluc** [comment] 2017-03-21 11:23
I just installed the new update, and …. YES it works

 

SuperSluc

 

Van: Nikolaj Olsson [mailto:notifications@github.com] 
Verzonden: dinsdag 21 maart 2017 09:50
Aan: SubtitleEdit/subtitleedit
CC: SuperSluc; Mention
Onderwerp: Re: [SubtitleEdit/subtitleedit] Cannot open video(mp4) file [Windows Update KB4013429] (#2292)

 

Fixed in Windows update KB4015438 :)
https://support.microsoft.com/en-us/help/4015438/windows-10-update-kb4015438

Can anyone confirm?

**Comment by ainafets** [comment] 2017-03-21 15:12
I had the same problem and finally by installing the new update everything seemed to be working fine.
There is still one problem though, in every version of SE the shortcut keys F9, F11 and F12 don't work.
It is very difficult to set start and end time by clicking the commands with the mouse. Any ideas?

**Comment by niksedk** [comment] 2017-03-21 15:57
@ainafets: thx for the info - please create a new issue for your shortcut problem.

**Comment by niksedk** [comment] 2017-03-21 16:09
Not getting much love from Microsoft. 
First a false positive in Windows Defender and now this Window Update issue...

**Closed by niksedk** 2017-03-21 16:09 UTC
