### ISSUE TITLE
[Feature] Hardsub to PGS

### ISSUE THREAD

**Issue by t2YU2m8l83** [SubtitleEdit/subtitleedit#4533] opened 2020-11-22 18:40 UTC
It would be great, if you could implement a feature, that extracts the differences between two video streams into images, that will then be converted to pgs subtitles. With this feature, you can feed the Programm one original stream and one hardsub stream to create pgs "softsubs". The function should be forgiving in some degree and not require 100% accurate colors and identical pixel positions for both streams. This way feeding two fullhd streams should generate pretty good results depending on the input.

**Comment by darnn** [comment] 2020-11-22 18:58
You're probably better off trying something like this: https://sourceforge.net/projects/videosubfinder/
Or otherwise googling things like "ocr subtitles from video" or "extract hardcoded subtitles" etc.

**Comment by OmrSi** [comment] 2020-11-22 19:00
https://github.com/SubtitleEdit/subtitleedit/issues/4395#issuecomment-700425087

**Comment by t2YU2m8l83** [comment] 2020-11-23 15:07
OCR for hardsubed videos had really suboptimal results in my cases. Processing power doesn't matter at all, but detecting parts of faces as letters (as VideoSubFinder did frequently) is not really something you can accept, if you have a large amount of hardsubed videos. A common use case for this would be, porting hardsubed web streams to the original bd release that isn't available in the sub language. Despite having access to the hardsubed stream, the clean stream without subs and the Blu-ray version, there is currently no efficient way, to simply distinct both web streams and get the sub for the Blu-ray.

**Comment by darnn** [comment] 2020-11-23 15:24
I agree the results aren't great, but it's still way beyond the scope of Subtitle Edit. Also, have you defined only the subtitle area in VideoSubFinder? I did get plenty of artifacts with it, but not faces, since they usually didn't appear at the bottom of the video anyway.

**Comment by t2YU2m8l83** [comment] 2020-11-23 17:44
I even got half a scene without any text from VideoSubFinder [https://ibb.co/rKhRwd4](https://ibb.co/rKhRwd4).

**Comment by darnn** [comment] 2020-11-23 17:55
But, once again, you seem to be trying to scan the entire video. VideoSubFinder allows you to define the specific area of the video to scan:
![VideoSubFinder](https://user-images.githubusercontent.com/19672444/99997381-c319fe80-2dc5-11eb-938f-549b0d8a444c.png)

**Comment by niksedk** [comment] 2020-11-23 20:44
Duplicate of #340

**Closed by niksedk** 2020-11-23 20:44 UTC

**Comment by soshial** [comment] 2022-02-16 03:18
Thank you so much, @[darnn](https://github.com/darnn), for your suggestion. VideoSubFinder worked like a charm with hardsubs of a small resolution video!
