### ISSUE TITLE
Title is messed up!

### ISSUE THREAD

**Issue by uckthis** [SubtitleEdit/subtitleedit#3225] opened 2018-12-11 04:16 UTC
Hey, 
After the latest beta update, build 164, this is what I see. Numbers constantly change. Why?
![untitled](https://user-images.githubusercontent.com/28671050/49778087-346d5d80-fd25-11e8-9eb4-d509f6367ef6.jpg)
Something on my end?

**Comment by uckthis** [comment] 2018-12-11 04:32
Also, do-not-break-after list is not working. Line gets broken without taking the do-not-break-after list into consideration.

Thank you.

**Comment by OmrSi** [comment] 2018-12-11 06:38
The first part is a duplicate of https://github.com/SubtitleEdit/subtitleedit/issues/3223

**Comment by uckthis** [comment] 2018-12-11 06:41
@OmrSi, good. Means the issue is global and not just me.

**Comment by niksedk** [comment] 2018-12-11 10:38
@uckthis: Could you provide an example?

**Comment by uckthis** [comment] 2018-12-11 10:45
@niksedk, My do-not-break-after list has a few words like a, the, and, I, I'm, etc. Since build 164, SE is ignoring that and breaking lines after those words. Today I worked about 7 hours on the SE and it continued to do so when I "Auto-break the text."

**Comment by OmrSi** [comment] 2018-12-11 12:11
@uckthis It's working here.
for example, I added "إلى" to the list, and in this sentence:
`ما رأيك في ترك المنزل والذهاب إلى الذهاب المنتزه مباشرة دون تأخير؟`

It breaks to, 
`ما رأيك في ترك المنزل والذهاب
إلى الذهاب المنتزه مباشرة دون تأخير؟`

But if I change "إلى" to another three-letter word, it breaks after it.


Though I've been meaning to ask about another one,
I added `، \b\w+\b` so it doesn't break with one word after the Arabic comma, but when I test it on something like this:
`ها ها ها ها ها ها ها ها ها، ها ها ها ها ها ها ها ها ها ها ها.`
it breaks to,
`ها ها ها ها ها ها ها ها ها، ها
ها ها ها ها ها ها ها ها ها ها.`
That's one word after the comma.
I don't know if there is something wrong with the Regex but SE finds it when using it with Find.

**Comment by uckthis** [comment] 2018-12-11 12:43
@OmrSi When I broke the text, at times it broke the text before and, or, I... That's just the coincidence. You break a text, you'll sure land on words that are already in the list. List is there to make sure there is a line break before the words. If it doesn't, even in one instance, that means that it's not properly working. It had been up until this point.

**Closed** 2018-12-11 18:10 UTC

**Comment by niksedk** [comment] 2018-12-11 18:13
beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.7/SubtitleEditBeta.zip

(sometimes the no-break-list was ignored due to some recent "improvements" to auto-break)

**Comment by OmrSi** [comment] 2018-12-13 19:22
@niksedk I still have that question, even when I add `، \b\w+\b` to the do-not-break-after-list,
`ها ها ها ها ها ها ها ها ها، ها ها ها ها ها ها ها ها ها ها ها.`
breaks to:
```
ها ها ها ها ها ها ها ها ها، ها
ها ها ها ها ها ها ها ها ها ها.
```
Is that a problem with my Regex?
