### ISSUE TITLE
Importing Timestamp from custom exporting.

### ISSUE THREAD

**Issue by rocknard** [SubtitleEdit/subtitleedit#4895] opened 2021-03-16 20:16 UTC
Hello.

I'm trying to import a "custom" timestamp, but the subtitle edit can't import it; however, it can export with the same format with "Export custom text format":

![image](https://i.ibb.co/dtKct99/FFX-timestamp.jpg)

Trying to import:

![image](https://i.ibb.co/bsLSFg8/FFX-import-plain-text.jpg)

Example (values in miliseconds):

18484,24045
25170,27062
28010,31318
32215,35645
83786,88338
89439,93493
94646,96471
97394,99997
101353,103432
104254,105806

Posibility to implement this?

**Comment by OmrSi** [comment] 2021-03-16 21:41
SE can't import custom formats yet.

Duplicate of https://github.com/SubtitleEdit/subtitleedit/issues/4221 or https://github.com/SubtitleEdit/subtitleedit/issues/2626

**Closed** 2022-08-28 16:40 UTC
