### ISSUE TITLE
Does not perform replace in the selected text!

### ISSUE THREAD

**Issue by dramirvf** [SubtitleEdit/subtitleedit#4197] opened 2020-05-24 05:21 UTC
I have selected several lines and I want to replace a word/character in the selected lines.
Regardless of what lines I have selected, the replacement will occur for all lines.

Any solutions?

**Comment by OmrSi** [comment] 2020-05-24 06:54
This is not an "issue".
SE simply doesn't have the "replace in selected lines" feature.
So, this is a duplicate of https://github.com/SubtitleEdit/subtitleedit/issues/2916

There is a trick to it if you'd like.
Select the lines you want to search in then Edit -> Insert Unicode symbol
Choose `♫` for example and a `♫` will be added to every line.
Now open replace, if you want to replace the word `now` with the word `know` for example in the lines you selected you would do:
![image](https://user-images.githubusercontent.com/20923700/82747697-7b79d200-9da4-11ea-95ff-3aae17401be3.png)


Then remove the symbols:
![image](https://user-images.githubusercontent.com/20923700/82747690-656c1180-9da4-11ea-89a5-371fdfe27c89.png)

**Closed** 2020-05-24 06:55 UTC
