### ISSUE TITLE
SubtitleEdit force closes when used simultaneously with MPC-HC/ K-Lite Pack.

### ISSUE THREAD

**Issue by NonVolatileHuman** [SubtitleEdit/subtitleedit#8055] opened 2024-03-22 20:51 UTC
For some reason, SE crashes if I play a video while editing the subtitles for another, or any other video for that matter. Which has cost me some time at least twice due to having to redo multiple lines that I have done before. Google was no help and I couldn't find any Autosave functionality in the software, any help is appreciated.

**Comment by niksedk** [comment] 2024-03-22 21:43
I need a lot more info... what video player are you using? What video? Logs?
Read more here: https://www.nikse.dk/subtitleedit/help#good-github-issue

Also, SE has an auto-back feature enabled by default. Check File - Restore auto-backup...

**Comment by NonVolatileHuman** [comment] 2024-03-23 00:30
Video package: K-Lite Codec Pack (18.2.4)
Video player: MPC-HC with MadVR
Latest SubtitleEdit Version 4.04
Win11 build 22631.3296

As for the issue itself, let's say I am editing the subs for video A, if I play Video B/W/O/N, etc… SE just closes from the taskbar/task manager, no pop-up, no prompts, nothing. It just disappears.

I don't know how to export logs from SE, unfortunately.

**Comment by niksedk** [comment] 2024-03-23 07:23
I mean what video player, you're using inside SE. See Options - Settings - Video player:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/d2c589c5-8157-4e3e-81b1-1fa9640b3b67)

I recommend mpv.

If SE is just closing without an error, it is most likely some codec problem outside of SE, which I can do nothing to fix, sorry.

**Comment by niksedk** [comment] 2024-03-23 07:25
Auto-backup is triggered by time (only is changes have been made)
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/0ff26f30-b112-463a-9f09-c4d1fd28d196)

**Comment by NonVolatileHuman** [comment] 2024-03-23 08:57
I tried re-downloading MPV as I thought there might be something wrong with the installation, but that didn't help. 
The odd thing was that when I switched to MPC-HC in the video player tab, the videos don't play, like at all.
DirectShow works, but the subs look terrible, so I can't use that unfortunately, I might contact the MPC-HC dev, but I think I should inform you first.

**Comment by niksedk** [comment] 2024-03-23 09:39
I'm not really sure what you the problem is...
You can try latest SE beta which download a newer mpv version: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.4/SubtitleEditBeta.zip

You could also try to update your gfx card drivers + check for Windows updates.

**Comment by NonVolatileHuman** [comment] 2024-03-23 09:55
The beta didn't work, still crashed. Windows is up-to-date, as for the GPU, there's a driver release around the corner, will wait for it and report back if the issue persists.

I will rename the issue for future reference.

**Comment by NonVolatileHuman** [comment] 2024-03-23 11:10
@niksedk found some info in the Event viewer!

Labeled “application error” :

_Faulting application name: SubtitleEdit.exe, version: 4.0.4.0, time stamp: 0x65f71054
Faulting module name: ucrtbase.dll, version: 10.0.22621.2506, time stamp: 0x097c794c
Exception code: 0xc0000005
Fault offset: 0x0000000000051bad
Faulting process id: 0x0x12D4
Faulting application start time: 0x0x1DA7D11BD6E7AD7
Faulting application path: C:\Program Files\Subtitle Edit\SubtitleEdit.exe
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
Report Id: dcf6e01e-1024-48ee-ab30-eedd09dec5f3
Faulting package full name: 
Faulting package-relative application ID:_ 

Another one labeled “.NET Runtime” : 
_Application: SubtitleEdit.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 00007FFB48561BAD_

I have both Desktop Runtime 6 & 8, don't know if that's relevant.

**Comment by niksedk** [comment] 2024-03-23 12:16
You could also try-reinstalling .net framework: https://dotnet.microsoft.com/en-us/download/dotnet-framework/net481

And Windows re-install might also help...

Not really anything I can do in SE I think.

**Closed by niksedk** 2024-03-23 12:16 UTC

**Comment by NonVolatileHuman** [comment] 2024-03-23 15:41
Isn't .Net 4.8.1 a bit too old?
Or does SE need that version specifically?

**Comment by niksedk** [comment] 2024-03-23 17:31
@clsid2: Thx, I did not know this. 
I'm not too interested in the world beyond the managed world, as these crashes happen in Windows code or in external codecs.
(and thx for your work :)

@NonVolatileHuman: SE requires the dotnet framework 4.8 runtime.
MS also has the donet 6-8, but applications written in these versions will not run on Linux as far as I know.
