### ISSUE TITLE
Windows Forms Thread Exception

### ISSUE THREAD

**Issue by Melllyna** [SubtitleEdit/subtitleedit#5648] opened 2021-12-29 12:23 UTC
Windows Forms Thread Exception
An application error occurred in Subtitle Edit 3.6.4.0. Please report at https://github.com/Subtitle Edit/subtitleedit/issues with the following information:
Error Message: Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index
Stack Trace: at System.ThrowHelper.ThrowArgumentOutOfRange Exception(ExceptionArgument argument, Exception Resource resource) at Nikse.Subtitle Edit.PluginLogic.PluginForm.LoadNames EtcWithCulture at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e) at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value) at Nikse. SubtitleEdit.PluginLogic.PluginForm.UseGoogleLangDetect(String text) at Nikse.Subtitle Edit.PluginLogic.PluginForm.AutoDetectLanguage at Nikse.Subtitle Edit.Plugin Logic.PluginForm.PluginForm_Shown(Object sender, EventArgs e) at System.Windows.Forms.Form.OnShown(EventArgs e) at System.Windows.Forms.Control.invokeMarshaledCallbackHelper(Object obj) at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state) at System.Windows.Forms.Control.Invoke

*****************
The issue is intermittent, but can be easily reproduced by closing the app and trying again multiple times.
If you go with retry, the error will go away, however spell check won't work as it won't offer any corrections. 
Somewhat similar to closed issue https://github.com/SubtitleEdit/subtitleedit/issues/4375
 
Steps to reproduce try to spell check subtitles using word.
![S83T5pTtDD](https://user-images.githubusercontent.com/95092281/147661672-8e42b4e3-306a-4e1d-80b1-99cc83d4971c.png)

**Comment by niksedk** [comment] 2021-12-29 12:42
Sorry, I don't have Word, so I cannot test this :(

**Comment by niksedk** [comment] 2022-01-06 17:14
Duplicate of #5406

**Closed by niksedk** 2022-01-06 17:14 UTC
