### ISSUE TITLE
Hard limit on Max. Characters per line

### ISSUE THREAD

**Issue by Estevarena** [SubtitleEdit/subtitleedit#7581] opened 2023-11-01 19:35 UTC
Would it be possible to add an optional limit to the maximum number of characters per line, that automatically moves the cursor to the next line, and maybe prevents you from writing on, when you reach the end of the subtitle?
Like MS Word and LO Writer do when you reach the margin of the page.
Maybe that already exists, but I couldn't find it.

**Comment by niksedk** [comment] 2023-11-01 19:37
Dupe of https://github.com/SubtitleEdit/subtitleedit/discussions/7580

**Closed** 2023-11-01 19:37 UTC
