### ISSUE TITLE
Release 3.6.3

### ISSUE THREAD

**Issue by niksedk** [SubtitleEdit/subtitleedit#5429] opened 2021-10-29 03:53 UTC
Time for yet another release :)

Most changes are probably for "Video - Generate video with burned-in subtitles" where a lot of new options are available.
(Cicking on the "Help" link will show ffmpeg docs depending on selected codec)

ASSA (Advanced Sub Station Alpha) support has also been improved. 
Leon Cheung has made a nice "ASSA draw" icon that will show up in the toolbar, if you have installed the "ASSA draw" plugin.

Many minor fixes and improvements: https://raw.githubusercontent.com/SubtitleEdit/subtitleedit/master/Changelog.txt

Beta link: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.2/SubtitleEditBeta.zip

NOTE: As version 3.6.2 had many false positives from anti-virus providers, 3.6.3 will not pack dll files into the "SubtitleEdit.exe" file, so SE will now consist of "SubtitleEdit.exe" and a lot of dll files.

Do let us know if you known/find any bugs :)

TODO:
- [x] Test ASSA format change
- [x] Test generate video w burned in subs
- [x] Test list view "replace all"
- [x] Test batch convert
- [x]  Test Tesseract OCR 5.00 RC1
- [x] General testing  (+ fixing bugs)

**Comment by LeonCheung** [comment] 2021-10-30 05:57
#5433 :)

**Comment by LeonCheung** [comment] 2021-10-31 13:38
> Also, does anyone have Win11 installed? Would be nice to know if SE works on Win11!

Just tested a little, it works well so far.

**Comment by moi15moi** [comment] 2021-10-31 14:05
The conversion ass --> srt does not work very well.

Initial .ass: https://uptobox.com/2865ai5agwqd
SRT: https://uptobox.com/dhy6owe261ta

In the srt file, it does not start with 1, it start with the line 80
```
80
01:10:19,860 --> 01:10:20,160
{\an2}Nes
```

But, it seems to deleted correctly the commentary and the tag except \an

**Comment by niksedk** [comment] 2021-10-31 14:41
@moi15moi: thx for the testing/info :)
Latest beta should now renumber: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.2/SubtitleEditBeta.zip

The `{\an<number>}` tags are kept on purpose - many people use the tags in srt and all major video players support them too.

**Comment by LeonCheung** [comment] 2021-10-31 15:27
Toggling off this option doesn't update the list view:

![image](https://user-images.githubusercontent.com/494788/139590713-3153f0ca-f42a-4f89-8026-5af097936b5d.png)

**Comment by niksedk** [comment] 2021-10-31 19:43
Also, latest beta has "list view replace all" rewritten for better performance in large files.

**Comment by niksedk** [comment] 2021-10-31 20:14
@LeonCheung: Color text if too wide works fine here:
![image](https://user-images.githubusercontent.com/1261331/139599799-ffd450bb-b643-495b-bbd1-bb4444bed7a3.png)

**Comment by LeonCheung** [comment] 2021-11-01 03:40
@niksedk build 247:

https://user-images.githubusercontent.com/494788/139618607-877400f3-5678-497d-bac2-1d53327302dc.mp4

It seems being updated by resizing the window though.

**Comment by niksedk** [comment] 2021-11-01 06:06
OK, found two optimizations regarding ctrl+a /  deselect - should help a little:
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.2/SubtitleEditBeta.zip

I cannot re-produce the issue from your mp4 video.

**Comment by LeonCheung** [comment] 2021-11-01 07:23
@niksedk What's interesting is that the response now depends on the line number you click again. e.g, if I deselect by clicking on the first line, then it will be really fast; but when I click on the last line, for example, it's still very slow. Tested with build 249, with a file with 2.5k lines.

**Comment by darnn** [comment] 2021-11-01 08:47
Not sure this is related, but since you mentioned ctrl+a optimizations:
When you have a timed subtitle file, in list view, if you select all and then press the home key (that is, to go to the first subtitle), SE seemingly cycles through every subtitle in the file in order before it actually switches to the first one:
![se-GIF 11-1-2021 10-39-00 AM](https://user-images.githubusercontent.com/19672444/139645039-b35cb007-ce96-4eaa-b83e-07c5e4a39ddc.gif)

This happens both before and with the latest beta.

And I also can't reproduce the issue from the video, for the record.

**Comment by LeonCheung** [comment] 2021-11-01 08:51
@darnn Yes. I can reproduce that in previous betas. But it's gone in the latest beta. Try it out. :)

**Comment by OmrSi** [comment] 2021-11-01 12:09
Reminds me of https://github.com/SubtitleEdit/subtitleedit/issues/3201

**Comment by niksedk** [comment] 2021-11-01 18:40
@OmrSi: yes, I think the old fix was buggy... could randomly change time codes while scrolling :(

How is latest beta with list view performance? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.2/SubtitleEditBeta.zip

**Comment by Samo99** [comment] 2021-11-01 19:59
I hoped this version will be the that have this request

https://github.com/SubtitleEdit/subtitleedit/issues/5276

**Comment by darnn** [comment] 2021-11-01 22:16
> How is latest beta with list view performance? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.2/SubtitleEditBeta.zip

Works great for me!

**Comment by OmrSi** [comment] 2021-11-01 23:33
Thanks. Seems to be working well here as well so far.

I had one case where the text box wouldn't change when changing the selected line until clicking twice on it, but it was fixed with a restart and I haven't been able to reproduce it so far.

**Comment by LeonCheung** [comment] 2021-11-02 05:37
Beta 257 is cool just.. I think invert selection (**Ctrl Shift I**) also needs a try-to-fix.  :)

**Comment by niksedk** [comment] 2021-11-02 15:30
@LeonCheung: thx - tried to fix the invert here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.2/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment] 2021-11-02 15:55
Just found something other cases that you can feel slow, especially with large files:

1. Ctrl-A then use **Replace** or **Replace all**.
2. Select a bunch of lines then **Replace**.
3. Select a bunch of lines then **Replace all**, when the  "Continue replace?" window pops up, click "**No**" or "**Cancel**".

**Comment by niksedk** [comment] 2021-11-02 16:06
@Samo99: How is this beta? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.2/SubtitleEditBeta.zip

**Comment by matmaggi** [comment] 2021-11-02 18:59
In Brazilian Portuguese the first two options have the same name in the "dialog style"
![image](https://user-images.githubusercontent.com/48259053/139927812-91f67770-2d95-4ca7-bd96-829f06e93167.png)

It should be:
With space = com espaço
Without space = sem espaço

**Comment by niksedk** [comment] 2021-11-02 19:07
@LeonCheung: thx - fixed a few more places... beta updated.

@matmaggi: thx - should be fixed in beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.2/SubtitleEditBeta.zip

**Comment by matmaggi** [comment] 2021-11-02 19:23
Hi @OmrSi (or Nikse?) Netflix Quality Checker for Brazilian Portuguese should be "Dual Speakers: Use a hyphen with space" after the last guideline update.

Besides that, I have tested some things and I think it's good to go. :)

**Comment by niksedk** [comment] 2021-11-02 19:50
thx @OmrSi  :)
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.2/SubtitleEditBeta.zip

**Comment by Samo99** [comment] 2021-11-02 21:15
> @Samo99: How is this beta? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.2/SubtitleEditBeta.zip

I tested it and it worked great without errors or miss calculation, but if you can add an option to source to let it auto without specifying a resolution case you know not all source files will be the same resolution.

![1](https://user-images.githubusercontent.com/12115578/139952129-907bf016-b5b8-4f9e-ac15-3454ee8d4173.PNG)

And if you may add "Scale Border and Shadow" to the batch convert cause the only way to enable it only if want to change the styles but if you enabled "use style from source" you can't bath it to the files.

**Comment by niksedk** [comment] 2021-11-02 21:19
@Samo99: thx for testing and suggestions :)
Ah, probably simpler just to remove "source res", right?

**Comment by Samo99** [comment] 2021-11-02 21:34
> @Samo99: thx for testing and suggestions :) Ah, probably simpler just to remove "source res", right?

Yes, that will be great.

**Comment by LeonCheung** [comment] 2021-11-03 04:32
@niksedk Now it's cool enough! 🥇

**Comment by darnn** [comment] 2021-11-03 08:32
> > How is latest beta with list view performance? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.2/SubtitleEditBeta.zip
> 
> Works great for me!

Actually, this broke again in the latest beta. Works fine in 252, but not in 276.

**Comment by niksedk** [comment] 2021-11-03 09:33
@darnn: What exactly is not working well for you?

**Comment by darnn** [comment] 2021-11-03 10:09
The same thing as before, if I use ctrl+a to select all the subtitles in list view and then press home, it cycles through every subtitle.

**Comment by niksedk** [comment] 2021-11-03 11:13
@darnn: thx, I must have reverted that back somehow... beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.2/SubtitleEditBeta.zip

**Comment by darnn** [comment] 2021-11-03 11:41
Yep, works fine now.

**Comment by JDTR75** [comment] 2021-11-03 20:28
I'm getting this flag by the antivirus:

![image](https://user-images.githubusercontent.com/1891941/140187507-628f9af6-66ee-4975-830c-e61927c97ee7.png)

**Comment by LeonCheung** [comment] 2021-11-04 03:19
@niksedk For offset-related shortcuts like "**set start/end** xxx **offset** xxx " , they are pretty slow with large files, though I can see that there are lots of lines to offset, which may cause performance issues. Just wonder if it is possible to have some perf improvement in this regard. 

For example. when offsetting like 2k lines, it cost me about 3 secs on a high-end PC. (that's also the reason I haven't recommended them in my tutorials yet, though they are still the best option for smaller files for now)

**Comment by niksedk** [comment] 2021-11-04 06:48
@JDTR75: Please report false positive to your anti-virus provider.
But this is much better: https://www.virustotal.com/gui/file/aa2dfc2c6f48892e8b7d78d8a82938d21a249d60ac0ceb2c9c8ed31b780877dc
At 3.6.2 release 28 anti-virus programs flagged SE!

**Comment by hugok79** [comment] 2021-11-04 10:18
> Also, does anyone have Win11 installed? Would be nice to know if SE works on Win11!

It works fine here:
Edition:	Windows 11 Home
Version:	21H2
Compilation: 22000.282

**Comment by niksedk** [comment] 2021-11-04 19:07
> 
> 
> @niksedk For offset-related shortcuts like "**set start/end** xxx **offset** xxx " , they are pretty slow with large files, though I can see that there are lots of lines to offset, which may cause performance issues. Just wonder if there could be any possible perf improvement in this regard.
> 
> For example. when offsetting like 2k lines, it cost me about 3 secs on a high-end PC. (that's also the reason I haven't recommended them in my tutorials yet, though they are still the best option for smaller files for now)

I've tried to optimize it... but it's still not fast, but a little better: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.2/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment] 2021-11-05 03:59
@niksedk I can tell it's now about 3x faster! 👍  However, after using "set **end**... offset...." shortcuts, the list stops updating. You can confirm it by clicking F2 twice, or try scrolling the list.

For the syntax coloring updating issue, I just tested it on a completely different PC, and it's the same problem. I've created a separate report since this thread is too long. See #5445.

**Comment by niksedk** [comment] 2021-11-05 20:11
@LeonCheung: is the above issue with "list stops updating" fixed?

Also, beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.2/SubtitleEditBeta.zip
(Updated Tesseract OCR to 5.00 rc1)

**Comment by OmrSi** [comment] 2021-11-06 01:20
@niksedk When you have a subtitle and an original subtitle and you translate selected lines via GT screen scraper, clicking `Save` after the auto-translation is done shows the `Save as…` dialog although it's the same subtitle.

**Comment by LeonCheung** [comment] 2021-11-06 04:20
@niksedk Not yet with build 305:


https://user-images.githubusercontent.com/494788/140597636-806f14ee-533f-48b8-88c5-1b9b40963d0f.mp4

**Comment by niksedk** [comment] 2021-11-06 08:59
@OmrSi: thx - the save issue should be fixed now: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.2/SubtitleEditBeta.zip

@LeonCheung; thx, the list view update issue should also be fixed in above beta.

**Comment by LeonCheung** [comment] 2021-11-06 09:11
@niksedk Cool, indeed. 👍

**Closed** 2021-11-11 10:22 UTC

**Comment by matmaggi** [comment] 2022-05-17 01:24
> In Brazilian Portuguese the first two options have the same name in the "dialog style" ![image](https://user-images.githubusercontent.com/48259053/139927812-91f67770-2d95-4ca7-bd96-829f06e93167.png)
> 
> It should be: With space = com espaço | Without space = sem espaço

Hi, @niksedk the same problem is happening again with 3.6.5

**Comment by niksedk** [comment] 2022-05-17 05:17
thx again :)

**Comment by hugok79** [comment] 2022-05-17 12:55
@niksedk Although I am not a native Brazilian, I can correct this, since Brazilians speak Portuguese.... (Brazilian Portuguese)
