### ISSUE TITLE
Feature Request: Merge/Copy empty line with previous line

### ISSUE THREAD

**Issue by ftfox** [SubtitleEdit/subtitleedit#7789] opened 2023-12-25 13:38 UTC
### When I use Merge max two lines in Auto-translate
![1](https://github.com/SubtitleEdit/subtitleedit/assets/56379264/ea0c1b8c-3451-4db0-b0ac-88047680ec2c)

### Many empty lines are often generated in the translation result
But this is not logical, because at this point both the English subtitles and the audio are playing, so the Chinese subtitles shouldn't just be displayed blank, it should continue to display the previous line of subtitles
![2](https://github.com/SubtitleEdit/subtitleedit/assets/56379264/982a0ffe-cc92-4ee3-a37f-43ac248b254c)

### So is there a way to quickly merge all blank lines with their previous, or to copy the previous line，like this
![3](https://github.com/SubtitleEdit/subtitleedit/assets/56379264/93c90276-c9c5-4b25-8dc0-bc134963e2f2)

**Comment by ftfox** [comment] 2023-12-25 13:46
### Subtitle sample used in this test
[test.zip](https://github.com/SubtitleEdit/subtitleedit/files/13766323/test.zip)

**Comment by niksedk** [comment] 2023-12-28 13:56
Auto-translate has been re-written in latest version (4.03)... could you test latest version?
https://github.com/SubtitleEdit/subtitleedit/releases

**Comment by ftfox** [comment] 2023-12-28 15:41
Thanks for the reply,

I tried the latest version (4.0.3) and found that the function "Merge max two lines" is no longer provided, I think it may be set to "No merging" by default, so this request may no longer make sense.
![3](https://github.com/SubtitleEdit/subtitleedit/assets/56379264/7abc6a60-230e-4824-9181-cf4b24867505)

### After testing, Auto-translate (to chinese) has a lot of problems in the latest version (4.0.3).
- [Significant reduction in translation speed](https://github.com/SubtitleEdit/subtitleedit/issues/7788)
- Many new bugs appeared (Check out the markers in the image below)
  1. Random break is added
  2. Translations are incorrectly split to the next line
  3. Certain sentences are ignored and not translated

![5](https://github.com/SubtitleEdit/subtitleedit/assets/56379264/cd6546c3-3504-44f9-adea-dea55adf2b1a)

Version 4.0.1 with the same settings doesn't have the above problem，Subtitle sample used in this test
[test2.zip](https://github.com/SubtitleEdit/subtitleedit/files/13787772/test2.zip)

**Comment by PureOcean** [comment] 2024-01-09 20:52
@niksedk

I've similar problems since version **4.0.2** and **4.0.3** (included last beta `#44`). In the Auto-Translate, some lines of the subtitles are empty and the sentences are splited/merged and therefore sync broken.

Finally, I was able to bring together the sentences of a subtitle that the issue could be reproduced at 4.0.3.

I attached are sample of the source subtitle and its Auto-Translated in 4.0.1 and 4.0.3. 
The Auto-Translate of version 4.0.1 sample correct sync. However, sync and line merges in the example in the version 4.0.3 are wrong.

(Source lang from: Swedish, to: Turkish, Service: Google Translate V1 API)

If you may compare the `"SE401_correct_sync_"` and `"SE403_uncorrect_sync_"` subtitles by WinMergeU, I hope you will determine where the problem is caused.

[SEdit403_auto-translate_sync_issue.zip](https://github.com/SubtitleEdit/subtitleedit/files/13878929/SEdit403_auto-translate_sync_issue.zip)

**Closed** 2024-04-20 18:22 UTC
Labels: wontfix
