### ISSUE TITLE
Error when trying to create subtitles with Audio to text

### ISSUE THREAD

**Issue by javiavid** [SubtitleEdit/subtitleedit#6297] opened 2022-09-30 07:17 UTC
When trying to create subtitles with Vosk this happens to me in some videos.
In others it works fine.

![image](https://user-images.githubusercontent.com/7627504/193212067-26c45b01-041c-4188-9916-72736df07b5a.png)

Windows 11 22h2
Subtitle Edit 3.6.7
Vosk_model_en_us-0.22
h264 mp4 video

**Comment by niksedk** [comment] 2022-09-30 07:18
Dupe of #6288 ?

**Comment by javiavid** [comment] 2022-09-30 11:40
I have read the other incidents and I just reinstalled subtitleedit, the player I have is the one that comes by default (directshow) and the version is the latest 3.6.7. I searched the blog but didn't find any beta.
I'll try to convert the failing videos to another format or try VLC to see if it fixes it.

**Comment by niksedk** [comment] 2022-09-30 11:42
Try using "mpv" as video player - and/or try the beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.7/SubtitleEditBeta.zip

**Comment by javiavid** [comment] 2022-09-30 12:20
I did some tests:

3.6.7 "standard" - Directshow and mpv - Error
3.6.7 beta 331 - Directshow, mpv, VLC - Error

Perhaps the file has an error, I have tried to reconvert it to h264 mp4 and it works correctly.

Would it be possible to have an option so that if there is an error, continue with the rest of the files automatically?

**Comment by niksedk** [comment] 2022-09-30 12:37
Ah, OK. thanks for the info. I will look into it.

**Closed** 2022-11-10 16:52 UTC
