### ISSUE TITLE
[Feature Request] Auto sync subtitles using waveform or audio timings

### ISSUE THREAD

**Issue by Dnkhatri** [SubtitleEdit/subtitleedit#4117] opened 2020-04-15 16:46 UTC
There is a github project that sort of does this and it accuracy is sometimes excellent other times not so good. But having the option inside Subtitle Edit would make the work flow easier for syncing subs if the algorithms used in this project are implemented and maybe improved.

https://github.com/kaegi/alass

**Comment by niksedk** [comment] 2020-04-15 17:07
SE has some related functionality... can suggest empty text placements based on waveform + adjust start time according to waveform (new shortcut in latest beta). 
But... even with clear audio, often a small sound precedes that actual talking.

Auto syncing a whole subtitle to waveform will probably need a lot of manual verifying... with seek silence in the waveform I can sync most subs with added/removed scenes in less than a minute.

**Comment by OmrSi** [comment] 2020-04-17 14:31
@niksedk A duplicate of https://github.com/SubtitleEdit/subtitleedit/issues/3717?

**Closed** 2020-04-17 14:42 UTC
